/** Plain-text quotation request summary for email attachment (PDF deferred without a PDF lib). */
export function buildQuotationRequestSummaryText(input: {
  referenceCode: string;
  vesselName?: string | null;
  vesselCode?: string | null;
  dueAt?: string | null;
  dockCycle?: string | null;
  plannedStart?: string | null;
  plannedEnd?: string | null;
  notes?: string | null;
  jobTitles?: string[];
  portalUrl?: string | null;
}): string {
  const lines = [
    "Actinium Dry Dock — Quotation Request Summary",
    "============================================",
    "",
    `Reference: ${input.referenceCode}`,
    input.vesselName || input.vesselCode
      ? `Vessel: ${[input.vesselName, input.vesselCode ? `(${input.vesselCode})` : null].filter(Boolean).join(" ")}`
      : null,
    input.dockCycle ? `Dock cycle: ${input.dockCycle}` : null,
    input.plannedStart ? `Planned start: ${input.plannedStart}` : null,
    input.plannedEnd ? `Planned end: ${input.plannedEnd}` : null,
    input.dueAt ? `Quote due: ${input.dueAt}` : null,
    input.notes ? `Notes: ${input.notes}` : null,
    "",
    "Jobs:",
    ...(input.jobTitles && input.jobTitles.length > 0
      ? input.jobTitles.map((t, i) => `  ${i + 1}. ${t}`)
      : ["  (none listed)"]),
    "",
    input.portalUrl ? `Open workspace: ${input.portalUrl}` : null,
    "",
    "Generated by Actinium Dry Dock",
  ];
  return lines.filter((l) => l != null).join("\n");
}
