#!/usr/bin/env bash
# E2E sync validation checklist.
set -euo pipefail

echo "=== Actinium-DD — E2E Sync Checklist ==="
echo ""
echo "Phase A — Infrastructure"
echo "[ ] Office: npm run relay:office-bootstrap"
echo "[ ] VPS:    VPS=174.138.189.162 npm run sync:phase-a"
echo "[ ] VPS:    relay-installation.local.env configured"
echo ""
echo "Phase B — Local apps"
echo "[ ] Mac:    copy local-apps/mac/ to ship Mac, run setup-postgres-mac.sh"
echo "[ ] Win:    copy local-apps/windows/, run setup-postgres-windows.ps1"
echo "[ ] Build:  npm run desktop:build && npm run local-app:package"
echo ""
echo "Phase C — Offline"
echo "[ ] Ship: create project, import 2 yard Excels, compare hull paint (offline)"
echo "[ ] Ship: double-click start-actinium-dd (sidecar + app)"
echo ""
echo "Phase D — Online office"
echo "[ ] Set OFFICE_AUTH_PASSWORD in .env, sign in at /login"
echo "[ ] Office portal: create project, invite yard"
echo ""
echo "Phase E — Yard + sync"
echo "[ ] Yard: open /quote/[token], submit quote or upload Excel"
echo "[ ] Office: yard status shows Submitted + date"
echo "[ ] Ship: Bucardo pull — yard quote visible locally"
echo "[ ] Office: lock spec line — ship pull overwrites"
echo ""
