import type { InputSectionDef } from "./types";

/** DD01 Special Survey — vessel pre-docking sections (Phase 2 starter pack). */
export const SPECIAL_SURVEY_VESSEL_SECTIONS: InputSectionDef[] = [
  {
    key: "hull_condition",
    label: "Hull condition",
    description: "Shell, bottom, and sea chest condition with photos.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    mandatory: true,
    attachmentRequired: true,
    fields: [
      { key: "shellCondition", label: "Shell condition", type: "textarea", required: true },
      { key: "bottomCondition", label: "Bottom condition", type: "textarea", required: true },
      { key: "seaChestCondition", label: "Sea chest condition", type: "textarea" },
      { key: "hullDamagePhotos", label: "Hull damage photos (file refs / notes)", type: "photos_note", required: true },
    ],
  },
  {
    key: "tank_condition",
    label: "Tank condition",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    mandatory: true,
    fields: [
      { key: "ballastTankCondition", label: "Ballast tank condition", type: "textarea", required: true },
      { key: "cargoTankCondition", label: "Cargo tank / hold condition", type: "textarea" },
      { key: "coatingBreakdown", label: "Coating breakdown", type: "textarea" },
      { key: "corrosionNotes", label: "Corrosion observations", type: "textarea" },
      { key: "mudSludgeQty", label: "Mud / sludge quantity", type: "text", unit: "m³" },
    ],
  },
  {
    key: "tailshaft",
    label: "Tailshaft",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    mandatory: true,
    fields: [
      { key: "runningHours", label: "Running hours since last withdrawal", type: "number", required: true },
      { key: "lastWithdrawalDate", label: "Last withdrawal date", type: "date" },
      { key: "sealLeakage", label: "Seal leakage", type: "select", options: [
        { value: "none", label: "None" },
        { value: "minor", label: "Minor" },
        { value: "moderate", label: "Moderate" },
        { value: "severe", label: "Severe" },
      ]},
      { key: "sternTubeOilConsumption", label: "Stern tube oil consumption", type: "text", unit: "L/day" },
      { key: "vibration", label: "Vibration / abnormal noise", type: "textarea" },
      { key: "bearingTemperature", label: "Bearing temperature notes", type: "text" },
    ],
  },
  {
    key: "propeller",
    label: "Propeller",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "bladeDamage", label: "Blade damage", type: "textarea" },
      { key: "cavitation", label: "Cavitation / erosion", type: "textarea" },
      { key: "ropeDamage", label: "Rope / fishing net damage", type: "textarea" },
      { key: "polishingRequired", label: "Polishing required", type: "boolean" },
      { key: "photosNote", label: "Photos", type: "photos_note" },
    ],
  },
  {
    key: "rudder",
    label: "Rudder & steering",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "steeringPerformance", label: "Steering gear performance", type: "textarea" },
      { key: "rudderStockLeakage", label: "Rudder stock leakage", type: "text" },
      { key: "abnormalVibration", label: "Abnormal vibration", type: "textarea" },
    ],
  },
  {
    key: "sea_valves",
    label: "Sea valves",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "valveListSummary", label: "Valve list / locations", type: "textarea" },
      { key: "lastOverhaulDates", label: "Last overhaul dates", type: "textarea" },
      { key: "leakageCondition", label: "Leakage / condition", type: "textarea" },
    ],
  },
  {
    key: "painting",
    label: "Painting & coating",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "currentPaintScheme", label: "Current paint scheme", type: "textarea" },
      { key: "antifoulingType", label: "Antifouling type", type: "text" },
      { key: "flatBottomArea", label: "Flat bottom area", type: "number", unit: "m²" },
      { key: "verticalBottomArea", label: "Vertical bottom area", type: "number", unit: "m²" },
      { key: "bootTopArea", label: "Boot top area", type: "number", unit: "m²" },
      { key: "topsideArea", label: "Topside area", type: "number", unit: "m²" },
      { key: "areaNotes", label: "Additional area notes", type: "textarea" },
      { key: "dftRequirement", label: "DFT requirement (owner / class)", type: "text", unit: "µm" },
    ],
  },
  {
    key: "machinery_readings",
    label: "Machinery readings",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "meRunningHours", label: "Main engine running hours", type: "number" },
      { key: "aeRunningHours", label: "Auxiliary engine running hours", type: "number" },
      { key: "overhaulDue", label: "Overhaul due items", type: "textarea" },
      { key: "turbochargerDue", label: "Turbocharger due", type: "text" },
      { key: "purifierPumpStatus", label: "Purifier / pump / compressor status", type: "textarea" },
    ],
  },
  {
    key: "vessel_documents",
    label: "Documents",
    pageKey: "vessel",
    moduleId: "documents",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "previousDdReport", label: "Previous dry dock report ref", type: "text" },
      { key: "classStatus", label: "Class status summary", type: "textarea" },
      { key: "certificateList", label: "Certificate list", type: "textarea" },
      { key: "drawingsNote", label: "Drawings available", type: "textarea" },
    ],
  },
];
