import type { InputSectionDef } from "./types";
import {
  HULL_CONDITION_OPTIONS,
  LOAD_LINE_WORK_OPTIONS,
} from "@/lib/superintendent/hullCondition";
import { TANK_CONDITION_FIELDS } from "@/lib/superintendent/tankCondition";
import {
  TAILSHAFT_REMOVAL_PLAN_OPTIONS,
  TAILSHAFT_SEAL_LEAKAGE_OPTIONS,
} from "@/lib/superintendent/tailshaftCondition";
import {
  PLANNED_PROPELLER_JOB_OPTIONS,
  PROPELLER_COATING_OPTIONS,
} from "@/lib/superintendent/propellerCondition";
import { RUDDER_TYPES } from "@/lib/superintendent/rudderCondition";

/** DD01 Special Survey — vessel pre-docking sections (Phase 2 starter pack). */
export const SPECIAL_SURVEY_VESSEL_SECTIONS: InputSectionDef[] = [
  {
    key: "hull_condition",
    label: "Hull condition",
    description: "Flat bottom, vertical bottom, and boot top condition, plus draft and statutory markings.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    mandatory: true,
    attachmentRequired: true,
    fields: [
      {
        key: "flatBottomCondition",
        label: "Flat bottom condition",
        type: "multiselect",
        required: true,
        options: [...HULL_CONDITION_OPTIONS],
      },
      {
        key: "verticalBottomCondition",
        label: "Vertical bottom condition",
        type: "multiselect",
        required: true,
        options: [...HULL_CONDITION_OPTIONS],
      },
      {
        key: "bootTopCondition",
        label: "Boot top condition",
        type: "multiselect",
        required: true,
        options: [...HULL_CONDITION_OPTIONS],
      },
      { key: "hullAreaNotes", label: "Additional hull notes", type: "textarea" },
      { key: "draftMarksForward", label: "Draft marks forward", type: "number", required: true },
      { key: "draftMarksMidship", label: "Draft marks midship", type: "number", required: true },
      { key: "draftMarksAft", label: "Draft marks aft", type: "number", required: true },
      { key: "plimsollMarks", label: "Plimsoll marks to paint", type: "number", required: true },
      {
        key: "loadLineWork",
        label: "Load line work",
        type: "select",
        required: true,
        options: [...LOAD_LINE_WORK_OPTIONS],
      },
      { key: "loadLineChangeNotes", label: "Load line change notes", type: "textarea" },
      { key: "paintFlagName", label: "Flag name to be painted", type: "boolean", required: true },
      { key: "paintImoNumber", label: "IMO number to be painted", type: "boolean", required: true },
      { key: "markingNotes", label: "Marking notes", type: "textarea" },
      { key: "photos", label: "Hull photos", type: "photos", required: true },
    ],
  },
  {
    key: "tank_condition",
    label: "Tank condition",
    description:
      "Tank counts and tank plan, then per-family jobs for ballast, cargo tanks or holds, engine-room tanks, and optional voids / cofferdams.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    mandatory: true,
    attachmentRequired: true,
    fields: [...TANK_CONDITION_FIELDS],
  },
  {
    key: "tailshaft",
    label: "Tailshaft",
    description:
      "Condition since last withdrawal, this docking plan, and last monitoring records for the yard.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    mandatory: true,
    fields: [
      { key: "runningHours", label: "Running hours since last withdrawal", type: "number", required: true },
      { key: "lastWithdrawalDate", label: "Last withdrawal date", type: "date" },
      {
        key: "sealLeakage",
        label: "Seal leakage",
        type: "select",
        options: [...TAILSHAFT_SEAL_LEAKAGE_OPTIONS],
      },
      { key: "sternTubeOilConsumption", label: "Stern tube oil consumption", type: "text", unit: "L/day" },
      { key: "vibration", label: "Vibration / abnormal noise", type: "textarea" },
      { key: "bearingTemperature", label: "Bearing temperature notes", type: "text" },
      {
        key: "removalPlan",
        label: "This docking plan",
        type: "select",
        required: true,
        options: [...TAILSHAFT_REMOVAL_PLAN_OPTIONS],
      },
      { key: "removalPlanNotes", label: "Plan notes", type: "textarea" },
      { key: "monitoringReadings", label: "Last monitoring data / readings", type: "files" },
      { key: "monitoringReport", label: "Last report", type: "files" },
    ],
  },
  {
    key: "propeller",
    label: "Propeller",
    description:
      "Blade condition, planned jobs this docking, optional coating job, photos, and last dry-dock propeller records.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "bladeDamage", label: "Blade damage", type: "textarea" },
      { key: "cavitation", label: "Cavitation / erosion", type: "textarea" },
      { key: "ropeDamage", label: "Rope / fishing net damage", type: "textarea" },
      { key: "polishingRequired", label: "Polishing required", type: "boolean" },
      {
        key: "plannedJobs",
        label: "Planned propeller jobs this docking",
        type: "multiselect",
        options: [...PLANNED_PROPELLER_JOB_OPTIONS],
      },
      {
        key: "coatingJob",
        label: "Silicone / anti-friction paint",
        type: "select",
        required: true,
        options: [...PROPELLER_COATING_OPTIONS],
      },
      { key: "lastDdJobs", label: "Last dry dock propeller jobs", type: "files" },
      { key: "photos", label: "Propeller photos", type: "photos" },
    ],
  },
  {
    key: "rudder",
    label: "Rudder & steering",
    description:
      "Rudder type, last recorded clearances and reports for the shipyard, plus steering condition notes.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      {
        key: "rudderType",
        label: "Rudder type",
        type: "select",
        required: true,
        options: [...RUDDER_TYPES],
      },
      { key: "rudderTypeOther", label: "Specify rudder type", type: "text" },
      {
        key: "propellerBearingClearance",
        label: "Propeller bearing (last clearance)",
        type: "number",
        unit: "mm",
        required: true,
      },
      {
        key: "neckCarrierBearingClearance",
        label: "Neck / carrier bearing clearance",
        type: "number",
        unit: "mm",
        required: true,
      },
      { key: "jumpingClearance", label: "Jumping clearance", type: "number", unit: "mm", required: true },
      { key: "upperPintleClearance", label: "Upper pintle last clearance", type: "number", unit: "mm" },
      { key: "lowerPintleClearance", label: "Lower pintle last clearance", type: "number", unit: "mm" },
      { key: "lastClearanceDate", label: "Date of last measurement", type: "date" },
      {
        key: "propellerBearingReport",
        label: "Last propeller bearing clearance report",
        type: "files",
      },
      {
        key: "rudderClearanceReport",
        label: "Last pintle / rudder clearance report",
        type: "files",
      },
      { key: "steeringPerformance", label: "Steering gear performance", type: "textarea" },
      { key: "rudderStockLeakage", label: "Rudder stock leakage", type: "textarea" },
      { key: "abnormalVibration", label: "Abnormal vibration", type: "textarea" },
    ],
  },
  {
    key: "sea_valves",
    label: "Sea valves",
    description:
      "Overboard and sea valves by group, with in situ vs workshop overhaul. Empty is allowed; rows stay until deleted.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "valves", label: "Sea valves", type: "text" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "painting",
    label: "Painting & coating",
    description:
      "Current scheme and DFT, then optional areas for the shipyard. Hull: flat bottom, vertical bottom, boot top, and topside — each zone has its own treatments (SA1, SA2, HP wash, etc.), yard %, primer/finish coats, and paint system.",
    pageKey: "vessel",
    moduleId: "scope",
    enteredBy: "vessel",
    reviewedBy: "superintendent",
    projectTypes: ["special_survey"],
    fields: [
      { key: "currentPaintScheme", label: "Current paint scheme", type: "textarea" },
      { key: "antifoulingType", label: "Antifouling type", type: "text" },
      { key: "dftRequirement", label: "DFT requirement (owner / class)", type: "text", unit: "µm" },
      { key: "areaNotes", label: "Additional area notes", type: "textarea" },
      { key: "flatBottomArea", label: "Hull — flat bottom area", type: "number", unit: "m²" },
      { key: "verticalBottomArea", label: "Hull — vertical bottom area", type: "number", unit: "m²" },
      { key: "bootTopArea", label: "Hull — boot top area", type: "number", unit: "m²" },
      { key: "topsideArea", label: "Hull — topside area", type: "number", unit: "m²" },
      {
        key: "areas",
        label:
          "Optional yard-painting areas (hull, ballast_tanks, cargo_holds, cargo_tanks, sea_chest, chain_locker, main_deck)",
        type: "text",
        placeholder:
          "Each: included, percentYard 0–100, primerCoats, finishCoats; extras may have areaM2",
      },
    ],
  },
];
