import type { MtilV2DomainRelease } from "./types";

/** V2.0.1 — Main Propulsion expanded component coverage. */
export const V201_MAIN_PROPULSION_COVERAGE = [
  "Cylinder cover",
  "Cylinder liner",
  "Piston",
  "Piston rings",
  "Stuffing box",
  "Crosshead",
  "Connecting rod",
  "Crankshaft",
  "Camshaft",
  "Fuel pumps",
  "Fuel injectors",
  "Exhaust valves",
  "Starting air distributor",
  "Turning gear",
  "Chain drive",
  "Thrust bearing",
  "Intermediate shaft",
  "Stern tube",
  "CPP/FPP",
  "Vibration measurements",
  "Alignment",
  "Deflection",
  "Timing",
  "Performance testing",
] as const;

/** V2.0 domain release registry — upgrades R0.x frameworks to production libraries. */
export const MTIL_V2_DOMAIN_REGISTRY: MtilV2DomainRelease[] = [
  {
    release: "V2.0.1",
    slug: "main-propulsion",
    name: "Main Propulsion (Expanded)",
    status: "pending",
    legacyPhaseId: 1,
    targetJobCount: { min: 1000, max: 1200 },
    idPrefix: "ENG-ME",
    deptCode: "ENG",
    description: "Expand ~140 R0.x jobs to 1,000–1,200 production-grade main engine jobs.",
    coverageAreas: [...V201_MAIN_PROPULSION_COVERAGE],
  },
  {
    release: "V2.0.2",
    slug: "auxiliary-machinery",
    name: "Auxiliary Machinery",
    status: "pending",
    legacyPhaseId: 2,
    targetJobCount: { min: 800, max: 800 },
    idPrefix: "ENG-AUX",
    deptCode: "ENG",
    description: "Expand auxiliary plant to ~800 normalized maintenance jobs.",
    coverageAreas: [
      "Auxiliary engines",
      "Boilers",
      "Purifiers",
      "Compressors",
      "Fresh water generators",
      "Heat exchangers",
      "OWS",
      "HVAC plant",
      "Steering gear",
      "Thrusters",
    ],
  },
  {
    release: "V2.0.3",
    slug: "pumps-piping",
    name: "Pumps & Piping",
    status: "pending",
    legacyPhaseId: 3,
    targetJobCount: { min: 1200, max: 1200 },
    idPrefix: "PVP",
    deptCode: "PVP",
    description: "Expand pumps, valves, and piping systems to ~1,200 jobs.",
    coverageAreas: [
      "Centrifugal pumps",
      "Positive displacement pumps",
      "Sea water systems",
      "Fresh water systems",
      "Fuel oil systems",
      "Lube oil systems",
      "Ballast systems",
      "Fire main",
      "Valves & actuators",
      "Piping surveys",
    ],
  },
  {
    release: "V2.0.4",
    slug: "deck-machinery",
    name: "Deck Machinery",
    status: "pending",
    legacyPhaseId: 4,
    targetJobCount: { min: 900, max: 900 },
    idPrefix: "DECK-DCG",
    deptCode: "DKC",
    description: "Expand deck machinery and access systems to ~900 jobs.",
    coverageAreas: [
      "Windlass & mooring",
      "Cranes & lifting",
      "Hatch covers",
      "Davits & access",
      "Cargo securing",
      "Deck hydraulics",
      "Capstans",
      "Gangways & ladders",
    ],
  },
  {
    release: "V2.0.5",
    slug: "hull-steel",
    name: "Hull & Steel",
    status: "pending",
    legacyPhaseId: 5,
    targetJobCount: { min: 900, max: 900 },
    idPrefix: "HUL-HUL",
    deptCode: "HUL",
    description: "Expand hull structure, steel renewal, and coatings to ~900 jobs.",
    coverageAreas: [
      "Shell plating",
      "Steel renewal",
      "Tank structures",
      "Coatings & anti-fouling",
      "Rudder & pintles",
      "Sea chests",
      "Anodes",
      "Propeller & tailshaft",
      "Structural surveys",
    ],
  },
  {
    release: "V2.0.6",
    slug: "electrical-automation",
    name: "Electrical & Automation",
    status: "pending",
    legacyPhaseId: 6,
    targetJobCount: { min: 1100, max: 1100 },
    idPrefix: "ELC-ELC",
    deptCode: "ELC",
    description: "Expand electrical, automation, and navigation to ~1,100 jobs.",
    coverageAreas: [
      "Generators",
      "Switchboards",
      "Motors & starters",
      "Automation & PLC",
      "Navigation equipment",
      "Communication systems",
      "Lighting",
      "Earthing & bonding",
      "Cable surveys",
    ],
  },
  {
    release: "V2.0.7",
    slug: "cargo-systems",
    name: "Cargo Systems",
    status: "pending",
    legacyPhaseId: 7,
    targetJobCount: { min: 1000, max: 1000 },
    idPrefix: "CGO-TNK",
    deptCode: "CGO",
    description: "Expand cargo tanks, pumps, and handling systems to ~1,000 jobs.",
    coverageAreas: [
      "Cargo tanks",
      "Cargo pumps",
      "Inert gas systems",
      "COW systems",
      "Ballast systems",
      "Tank gauging",
      "Vapor systems",
      "Cargo lines & valves",
    ],
  },
  {
    release: "V2.0.8",
    slug: "lsa-ffa",
    name: "LSA / FFA",
    status: "pending",
    legacyPhaseId: 8,
    targetJobCount: { min: 700, max: 700 },
    idPrefix: "SAF-LSA",
    deptCode: "SAF",
    description: "Expand life saving, fire fighting, and safety equipment to ~700 jobs.",
    coverageAreas: [
      "Lifeboats",
      "Rescue boats",
      "Life rafts",
      "Launching appliances",
      "Davit systems",
      "Fixed fire fighting",
      "Portable extinguishers",
      "Accommodation safety",
      "Safety equipment surveys",
    ],
  },
];

export function getV2DomainByRelease(release: string): MtilV2DomainRelease | undefined {
  return MTIL_V2_DOMAIN_REGISTRY.find((d) => d.release === release);
}

export function getV2DomainByLegacyPhase(phaseId: number): MtilV2DomainRelease | undefined {
  return MTIL_V2_DOMAIN_REGISTRY.find((d) => d.legacyPhaseId === phaseId);
}
