import { ServiceType, SERVICE_TYPE_LABELS } from "@/lib/types/vendor";

/** From address for vendor registration invites and login verification codes */
export const VENDOR_REGISTRATION_FROM_EMAIL = "welcome@actinium-sm.org";

/** Display name shown as the inviter in vendor registration emails */
export const VENDOR_REGISTRATION_INVITER_NAME =
  "Actinium-sm.org Ship manager application";

/** Shown after vendor submits registration (UI + API). */
export const VENDOR_REGISTRATION_SUBMITTED_MESSAGE =
  "Your registration has been submitted. Portal access will be enabled after verification by Admin team, you will receive email for the same.";

/** Footer for autogenerated vendor registration emails */
export const VENDOR_REGISTRATION_AUTO_EMAIL_FOOTER =
  "This is an autogenerated email from the Actinium Platform. Please do not reply to this email.";

/** Shipping-industry products & services vendors may offer */
export const VENDOR_PRODUCT_SERVICE_OPTIONS = [
  ...Object.values(ServiceType).map((value) => ({
    value,
    label: SERVICE_TYPE_LABELS[value as ServiceType],
  })),
  { value: "PROVISIONS", label: "Provisions / Bonded stores" },
  { value: "REPAIRS", label: "Repairs / riding teams" },
  { value: "SURVEYS", label: "Surveys / inspections / calibration" },
  { value: "WASTE", label: "Waste / garbage / sludge" },
  { value: "FRESH_WATER", label: "Fresh water / supplies" },
  { value: "LOGISTICS", label: "Logistics / freight forwarding" },
  { value: "MEDICAL", label: "Medical / travel / crew welfare" },
  { value: "IT_COMMS", label: "IT / communications" },
  { value: "LEGAL_CLASS", label: "Legal / classification liaison" },
] as const;

export const VENDOR_CURRENCY_OPTIONS = [
  "USD",
  "EUR",
  "GBP",
  "SGD",
  "AED",
  "INR",
  "CNY",
  "JPY",
  "AUD",
  "HKD",
] as const;

export const ONBOARDING_STEPS = [
  "details",
  "documents",
  "contacts",
  "legal",
  "banking",
  "overview",
] as const;

export type OnboardingStep = (typeof ONBOARDING_STEPS)[number];

export type VendorContactRow = {
  id?: string;
  role: string;
  name: string;
  email: string;
  phone: string;
  isPrimary?: boolean;
};

export type VendorDocumentRow = {
  id?: string;
  type: "REGISTRATION" | "VAT_CERTIFICATE" | "BANK_LETTER" | "OTHER";
  fileName: string;
  fileUrl: string;
  uploadedAt?: string;
};

export type VendorOnboardingData = {
  details?: {
    name?: string;
    companyRegistrationNumber?: string;
    preferredCurrency?: string;
    vatNumber?: string;
    productDescription?: string;
    serviceTypes?: string[];
    portIds?: string[];
    phone?: string;
    address?: string;
    city?: string;
    country?: string;
    contactPerson?: string;
    secondaryEmail?: string;
  };
  documents?: VendorDocumentRow[];
  contacts?: VendorContactRow[];
  legal?: {
    termsAccepted?: boolean;
    antiBriberyAccepted?: boolean;
    dataProtectionAccepted?: boolean;
    sanctionsCompliance?: boolean;
    notes?: string;
  };
  banking?: {
    bankName?: string;
    accountHolderName?: string;
    accountNumber?: string;
    iban?: string;
    swiftCode?: string;
    bankAddress?: string;
    verificationContactName?: string;
    verificationContactPhone?: string;
    verificationContactEmail?: string;
  };
};

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;

export function isValidVendorEmail(email: string): boolean {
  const t = email.trim();
  if (!t || t.length > 254) return false;
  return EMAIL_RE.test(t);
}

export function isValidVendorPhone(phone: string): boolean {
  const digits = phone.replace(/\D/g, "");
  return digits.length >= 8 && digits.length <= 15;
}

export function normalizeVendorEmail(email: string): string {
  return email.trim().toLowerCase();
}

export function onboardingStepIndex(step: OnboardingStep): number {
  return ONBOARDING_STEPS.indexOf(step);
}

export function validateOnboardingDetails(
  details: NonNullable<VendorOnboardingData["details"]>
): string | null {
  if (!details.name?.trim()) return "Company name is required";
  if (!details.companyRegistrationNumber?.trim()) return "Company registration number is required";
  if (!details.preferredCurrency?.trim()) return "Order currency is required";
  if (!details.country?.trim()) return "Country is required";
  if (!details.address?.trim()) return "Address is required";
  if (!details.contactPerson?.trim()) return "Primary contact name is required";
  if (!details.phone?.trim()) return "Phone number is required";
  if (!isValidVendorPhone(details.phone)) return "Enter a valid phone number (8–15 digits)";
  if (details.secondaryEmail?.trim() && !isValidVendorEmail(details.secondaryEmail)) {
    return "Secondary email is invalid";
  }
  if (!details.serviceTypes?.length) return "Select at least one product or service";
  if (!details.portIds?.length) return "Select at least one port where you provide services";
  return null;
}

export function validateOnboardingContacts(contacts: VendorContactRow[]): string | null {
  if (!contacts.length) return "Add at least one contact";
  const sales = contacts.find((c) => c.role.toLowerCase().includes("sales"));
  if (!sales) return "Add a Sales team contact";
  for (const c of contacts) {
    if (!c.name?.trim()) return "Each contact needs a name";
    if (!c.email?.trim() || !isValidVendorEmail(c.email)) return `Invalid email for contact ${c.name || ""}`;
    if (!c.phone?.trim() || !isValidVendorPhone(c.phone)) {
      return `Invalid phone for contact ${c.name || ""}`;
    }
  }
  return null;
}

export function validateOnboardingBanking(
  banking: NonNullable<VendorOnboardingData["banking"]>
): string | null {
  if (!banking.bankName?.trim()) return "Bank name is required";
  if (!banking.accountHolderName?.trim()) return "Account holder name is required";
  if (!banking.accountNumber?.trim() && !banking.iban?.trim()) {
    return "Account number or IBAN is required";
  }
  if (!banking.swiftCode?.trim()) return "SWIFT / BIC code is required";
  if (!banking.verificationContactName?.trim()) return "Bank verification contact name is required";
  if (!banking.verificationContactPhone?.trim()) return "Bank verification contact phone is required";
  if (!isValidVendorPhone(banking.verificationContactPhone)) {
    return "Bank verification contact phone is invalid";
  }
  if (
    banking.verificationContactEmail?.trim() &&
    !isValidVendorEmail(banking.verificationContactEmail)
  ) {
    return "Bank verification contact email is invalid";
  }
  return null;
}

export function validateOnboardingLegal(
  legal: NonNullable<VendorOnboardingData["legal"]>
): string | null {
  if (!legal.termsAccepted) return "Accept the terms and conditions";
  if (!legal.antiBriberyAccepted) return "Confirm anti-bribery compliance";
  if (!legal.dataProtectionAccepted) return "Confirm data protection policy";
  if (!legal.sanctionsCompliance) return "Confirm sanctions compliance";
  return null;
}
