import type { PermissionSeed } from "@/lib/rbac/types";

/** Permission catalog — pages (UI) + actions (API). Keys are stable identifiers. */
export const PERMISSIONS: PermissionSeed[] = [
  // —— Platform (Developer Admin) ——
  {
    key: "platform.tenant.manage",
    module: "platform",
    appSurface: "platform",
    description: "Manage tenants and licenses",
  },
  {
    key: "platform.config.manage",
    module: "platform",
    appSurface: "platform",
    description: "System configuration and feature flags",
  },
  {
    key: "page.platform.admin",
    module: "page",
    resource: "/platform",
    appSurface: "platform",
    description: "Developer admin console",
  },

  // —— Office pages ——
  {
    key: "page.office.projects",
    module: "page",
    resource: "/projects",
    appSurface: "office",
    description: "Project list",
    sortOrder: 10,
  },
  {
    key: "page.office.projects.new",
    module: "page",
    resource: "/projects/new",
    appSurface: "office",
    description: "Create project",
    sortOrder: 11,
  },
  {
    key: "page.office.project.overview",
    module: "page",
    resource: "/projects/[id]#overview",
    appSurface: "office",
    description: "Project overview tab",
    sortOrder: 20,
  },
  {
    key: "page.office.project.categories",
    module: "page",
    resource: "/projects/[id]#categories",
    appSurface: "office",
    description: "Cost categories tab",
    sortOrder: 21,
  },
  {
    key: "page.office.project.spec",
    module: "page",
    resource: "/projects/[id]#spec",
    appSurface: "office",
    description: "Spec editor tab",
    sortOrder: 22,
  },
  {
    key: "page.office.project.yards",
    module: "page",
    resource: "/projects/[id]#yards",
    appSurface: "office",
    description: "Yard invites tab",
    sortOrder: 23,
  },
  {
    key: "page.office.project.comparison",
    module: "page",
    resource: "/projects/[id]#comparison",
    appSurface: "office",
    description: "Comparison matrix tab",
    sortOrder: 24,
  },
  {
    key: "page.office.admin",
    module: "page",
    resource: "/admin",
    appSurface: "office",
    description: "Admin module home",
    sortOrder: 29,
  },
  {
    key: "page.office.admin.access",
    module: "page",
    resource: "/admin/access",
    appSurface: "office",
    description: "Page access matrix",
    sortOrder: 36,
  },
  {
    key: "page.office.admin.companies",
    module: "page",
    resource: "/admin/companies",
    appSurface: "office",
    description: "Company management",
    sortOrder: 30,
  },
  {
    key: "page.office.admin.vessels",
    module: "page",
    resource: "/admin/vessels",
    appSurface: "office",
    description: "Vessel management",
    sortOrder: 31,
  },
  {
    key: "page.office.admin.employees",
    module: "page",
    resource: "/admin/employees",
    appSurface: "office",
    description: "Employee management",
    sortOrder: 32,
  },
  {
    key: "page.office.admin.crewCredentials",
    module: "page",
    resource: "/admin/crew-credentials",
    appSurface: "office",
    description: "Vessel crew credential creation",
    sortOrder: 33,
  },
  {
    key: "page.office.admin.shipyards",
    module: "page",
    resource: "/admin/shipyards",
    appSurface: "office",
    description: "Shipyard organization management",
    sortOrder: 37,
  },
  {
    key: "page.office.admin.externalVendors",
    module: "page",
    resource: "/admin/external-vendors",
    appSurface: "office",
    description: "External vendor organization management",
    sortOrder: 38,
  },
  {
    key: "page.office.admin.users",
    module: "page",
    resource: "/admin/users",
    appSurface: "office",
    description: "User management (legacy)",
    sortOrder: 34,
  },
  {
    key: "page.office.admin.roles",
    module: "page",
    resource: "/admin/roles",
    appSurface: "office",
    description: "Role and permission management",
    sortOrder: 35,
  },

  // —— Superintendent (dry dock) ——
  {
    key: "page.superintendent.dashboard",
    module: "page",
    resource: "/superintendent",
    appSurface: "office",
    description: "Superintendent module home",
    sortOrder: 100,
  },
  {
    key: "page.superintendent.projects",
    module: "page",
    resource: "/superintendent/projects",
    appSurface: "office",
    description: "Dry dock project list",
    sortOrder: 101,
  },
  {
    key: "page.superintendent.projectWorkspace",
    module: "page",
    resource: "/superintendent/projects/[id]",
    appSurface: "office",
    description: "Dry dock project workspace",
    sortOrder: 102,
  },
  {
    key: "page.superintendent.procurement",
    module: "page",
    resource: "/superintendent/projects/[id]/procurement",
    appSurface: "office",
    description: "Project procurement and requisitions",
    sortOrder: 103,
  },
  {
    key: "page.superintendent.budget",
    module: "page",
    resource: "/superintendent/budget",
    appSurface: "office",
    description: "Budget and variations",
    sortOrder: 104,
  },
  {
    key: "page.superintendent.monitoring",
    module: "page",
    resource: "/superintendent/monitoring",
    appSurface: "office",
    description: "Daily reports and progress monitoring",
    sortOrder: 105,
  },
  {
    key: "page.superintendent.documents",
    module: "page",
    resource: "/superintendent/projects/[id]/documents",
    appSurface: "office",
    description: "Project document control",
    sortOrder: 106,
  },
  {
    key: "page.superintendent.closeout",
    module: "page",
    resource: "/superintendent/projects/[id]/closeout",
    appSurface: "office",
    description: "Project closeout checklist",
    sortOrder: 107,
  },
  {
    key: "page.superintendent.spares",
    module: "page",
    resource: "/superintendent/spares",
    appSurface: "office",
    description: "Spares and inventory tracking",
    sortOrder: 108,
  },
  {
    key: "page.superintendent.approvals",
    module: "page",
    resource: "/superintendent/approvals",
    appSurface: "office",
    description: "Approval inbox and sign-offs",
    sortOrder: 109,
  },
  {
    key: "page.superintendent.vesselRequisitions",
    module: "page",
    resource: "/superintendent/vessel-requisitions",
    appSurface: "office",
    description: "Vessel requisition bank",
    sortOrder: 110,
  },
  {
    key: "page.superintendent.vesselJobs",
    module: "page",
    resource: "/superintendent/vessel-jobs",
    appSurface: "office",
    description: "Vessel job bank review",
    sortOrder: 111,
  },
  {
    key: "page.superintendent.planning",
    module: "page",
    resource: "/superintendent/planning",
    appSurface: "office",
    description: "Milestones, risks, and checklist planning",
    sortOrder: 112,
  },
  {
    key: "page.superintendent.jobs",
    module: "page",
    resource: "/superintendent/jobs",
    appSurface: "office",
    description: "Master job library",
    sortOrder: 113,
  },
  {
    key: "page.superintendent.vessels",
    module: "page",
    resource: "/superintendent/vessels",
    appSurface: "office",
    description: "Vessel fleet under superintendent scope",
    sortOrder: 114,
  },

  // —— Department dashboards ——
  {
    key: "page.office.department.executive",
    module: "page",
    resource: "/office/executive",
    appSurface: "office",
    description: "Executive approval inbox and KPIs",
    sortOrder: 120,
  },
  {
    key: "page.office.department.fleet",
    module: "page",
    resource: "/office/fleet",
    appSurface: "office",
    description: "Fleet performance dashboard",
    sortOrder: 121,
  },
  {
    key: "page.office.department.hseq",
    module: "page",
    resource: "/office/hseq",
    appSurface: "office",
    description: "HSEQ incidents, audits, and ISM",
    sortOrder: 122,
  },
  {
    key: "page.office.department.crewing",
    module: "page",
    resource: "/office/crewing",
    appSurface: "office",
    description: "Crew matrix and certification tracking",
    sortOrder: 123,
  },
  {
    key: "page.office.procurement",
    module: "page",
    resource: "/office/procurement",
    appSurface: "office",
    description: "Office procurement strategy and vendor approval",
    sortOrder: 124,
  },
  {
    key: "page.office.accounts",
    module: "page",
    resource: "/office/accounts",
    appSurface: "office",
    description: "Accounts control and invoice verification",
    sortOrder: 125,
  },

  // —— Platform operations ——
  {
    key: "page.platform.monitor",
    module: "page",
    resource: "/platform/monitor",
    appSurface: "platform",
    description: "Infrastructure monitoring and alerts",
    sortOrder: 130,
  },
  {
    key: "page.platform.operator",
    module: "page",
    resource: "/platform/operator",
    appSurface: "platform",
    description: "Sync queues and import job monitor",
    sortOrder: 131,
  },

  // —— External party portals ——
  {
    key: "page.external.portal",
    module: "page",
    resource: "/external",
    appSurface: "yard",
    description: "External vendor portal home",
    sortOrder: 140,
  },
  {
    key: "page.external.class",
    module: "page",
    resource: "/external/class",
    appSurface: "yard",
    description: "Class surveyor read-only access",
    sortOrder: 141,
  },
  {
    key: "page.external.flag",
    module: "page",
    resource: "/external/flag",
    appSurface: "yard",
    description: "Flag state statutory access",
    sortOrder: 142,
  },
  {
    key: "page.external.owner",
    module: "page",
    resource: "/external/owner",
    appSurface: "yard",
    description: "Owner representative project oversight",
    sortOrder: 143,
  },
  {
    key: "page.external.auditor",
    module: "page",
    resource: "/external/auditor",
    appSurface: "yard",
    description: "External auditor compliance access",
    sortOrder: 144,
  },

  // —— Ship Access machinery (additional) ——
  {
    key: "page.shipAccess.machineryDashboard",
    module: "page",
    resource: "/ship-access/machinery",
    appSurface: "vessel",
    description: "Machinery health dashboard",
    sortOrder: 74,
  },
  {
    key: "page.shipAccess.machineryRunningHours",
    module: "page",
    resource: "/ship-access/machinery/running-hours",
    appSurface: "vessel",
    description: "Machinery running hours by asset",
    sortOrder: 75,
  },
  {
    key: "page.shipAccess.machineryParameters",
    module: "page",
    resource: "/ship-access/machinery/parameters",
    appSurface: "vessel",
    description: "Machinery parameter readings",
    sortOrder: 76,
  },
  {
    key: "page.shipAccess.machineryCondition",
    module: "page",
    resource: "/ship-access/machinery/condition",
    appSurface: "vessel",
    description: "Machinery condition reports",
    sortOrder: 77,
  },
  {
    key: "page.shipAccess.dryDockDashboard",
    module: "page",
    resource: "/ship-access/dry-dock",
    appSurface: "vessel",
    description: "Dry dock readiness dashboard",
    sortOrder: 78,
  },
  {
    key: "page.shipAccess.dryDockJobs",
    module: "page",
    resource: "/ship-access/dry-dock/jobs",
    appSurface: "vessel",
    description: "Dry dock scope jobs",
    sortOrder: 79,
  },
  {
    key: "page.shipAccess.dryDockJobs.new",
    module: "page",
    resource: "/ship-access/dry-dock/jobs/new",
    appSurface: "vessel",
    description: "Add dry dock scope job",
    sortOrder: 80,
  },
  {
    key: "page.shipAccess.pms",
    module: "page",
    resource: "/ship-access/pms",
    appSurface: "vessel",
    description: "Planned maintenance schedule",
    sortOrder: 83,
  },

  // —— Desktop pages ——
  {
    key: "page.desktop.jobs",
    module: "page",
    resource: "desktop://jobs",
    appSurface: "desktop",
    description: "Desktop job list and comparison",
    sortOrder: 40,
  },
  {
    key: "page.desktop.sync",
    module: "page",
    resource: "desktop://sync",
    appSurface: "desktop",
    description: "Sync status panel",
    sortOrder: 41,
  },

  // —— Yard portal ——
  {
    key: "page.yard.quote",
    module: "page",
    resource: "/quote/[token]",
    appSurface: "yard",
    description: "Shipyard quote portal",
    sortOrder: 50,
  },

  // —— Shipyard execution portal ——
  {
    key: "page.shipyard.dashboard",
    module: "page",
    resource: "/shipyard",
    appSurface: "yard",
    description: "Shipyard execution dashboard",
    sortOrder: 60,
  },
  {
    key: "page.shipyard.projects",
    module: "page",
    resource: "/shipyard/projects",
    appSurface: "yard",
    description: "Active execution projects",
    sortOrder: 61,
  },
  {
    key: "page.shipyard.workshops",
    module: "page",
    resource: "/shipyard/workshops",
    appSurface: "yard",
    description: "Workshop job boards",
    sortOrder: 62,
  },
  {
    key: "page.shipyard.planning",
    module: "page",
    resource: "/shipyard/planning",
    appSurface: "yard",
    description: "Master schedule and dependencies",
    sortOrder: 63,
  },
  {
    key: "page.shipyard.execution",
    module: "page",
    resource: "/shipyard/execution",
    appSurface: "yard",
    description: "Daily progress and registers",
    sortOrder: 64,
  },
  {
    key: "page.shipyard.commercial",
    module: "page",
    resource: "/shipyard/commercial",
    appSurface: "yard",
    description: "Variations, work done, completion",
    sortOrder: 65,
  },
  {
    key: "page.shipyard.tender",
    module: "page",
    resource: "/shipyard/tender",
    appSurface: "yard",
    description: "Tender and RFQ workflow",
    sortOrder: 66,
  },

  // —— Ship Access (onboard) ——
  {
    key: "page.shipAccess.dashboard",
    module: "page",
    resource: "/ship-access",
    appSurface: "vessel",
    description: "Ship Access overview",
    sortOrder: 70,
  },
  {
    key: "page.shipAccess.jobs",
    module: "page",
    resource: "/ship-access/jobs",
    appSurface: "vessel",
    description: "View vessel job submissions",
    sortOrder: 71,
  },
  {
    key: "page.shipAccess.jobs.new",
    module: "page",
    resource: "/ship-access/jobs/new",
    appSurface: "vessel",
    description: "Create vessel scope jobs",
    sortOrder: 72,
  },
  {
    key: "page.shipAccess.jobs.edit",
    module: "page",
    resource: "/ship-access/jobs/*/edit",
    appSurface: "vessel",
    description: "Update draft vessel jobs",
    sortOrder: 73,
  },
  {
    key: "page.shipAccess.machineryHours",
    module: "page",
    resource: "/ship-access/machinery-hours",
    appSurface: "vessel",
    description: "Machinery running hours",
    sortOrder: 74,
  },
  {
    key: "page.shipAccess.defects",
    module: "page",
    resource: "/ship-access/defects",
    appSurface: "vessel",
    description: "View vessel defect reports",
    sortOrder: 75,
  },
  {
    key: "page.shipAccess.defects.new",
    module: "page",
    resource: "/ship-access/defects/new",
    appSurface: "vessel",
    description: "Report machinery defects",
    sortOrder: 76,
  },
  {
    key: "page.shipAccess.defects.edit",
    module: "page",
    resource: "/ship-access/defects/*/edit",
    appSurface: "vessel",
    description: "Update draft vessel defects",
    sortOrder: 77,
  },
  {
    key: "page.shipAccess.defects.masterReview",
    module: "page",
    resource: "/ship-access/defects#master-review",
    appSurface: "vessel",
    description: "Master approve or reject defects",
    sortOrder: 78,
  },
  {
    key: "page.shipAccess.purchase",
    module: "page",
    resource: "/ship-access/purchase",
    appSurface: "vessel",
    description: "View purchase requisitions",
    sortOrder: 79,
  },
  {
    key: "page.shipAccess.purchase.new",
    module: "page",
    resource: "/ship-access/purchase/new",
    appSurface: "vessel",
    description: "Create spares requisitions",
    sortOrder: 80,
  },
  {
    key: "page.shipAccess.purchase.edit",
    module: "page",
    resource: "/ship-access/purchase/*/edit",
    appSurface: "vessel",
    description: "Update draft requisitions",
    sortOrder: 81,
  },
  {
    key: "page.shipAccess.purchase.masterReview",
    module: "page",
    resource: "/ship-access/purchase#master-review",
    appSurface: "vessel",
    description: "Master approve requisitions",
    sortOrder: 82,
  },
  { key: "ship.job.create", module: "ship", description: "Create vessel job bank entries" },
  { key: "ship.job.read", module: "ship", description: "View own vessel job submissions" },
  { key: "ship.job.update", module: "ship", description: "Update draft vessel jobs" },
  { key: "ship.job.masterApprove", module: "ship", description: "Master endorse CE-approved vessel scope jobs" },
  { key: "ship.machinery.read", module: "ship", description: "View vessel machinery running hours" },
  { key: "ship.machinery.update", module: "ship", description: "Update vessel machinery running hours" },
  { key: "ship.defect.create", module: "ship", description: "Report vessel machinery defects" },
  { key: "ship.defect.read", module: "ship", description: "View vessel defect reports" },
  { key: "ship.defect.update", module: "ship", description: "Update or cancel draft vessel defects" },
  { key: "ship.defect.masterApprove", module: "ship", description: "Master approve or reject submitted defects" },
  { key: "ship.purchase.read", module: "ship", description: "View purchase and requisitions module" },
  { key: "ship.purchase.create", module: "ship", description: "Create spares requisitions from approved defects" },
  { key: "ship.purchase.update", module: "ship", description: "Update or cancel draft requisitions" },
  { key: "ship.purchase.masterApprove", module: "ship", description: "Master approve or reject submitted requisitions" },

  // —— Shipyard execution actions ——
  { key: "yard.execution.read", module: "yard", description: "View yard execution projects and jobs" },
  { key: "yard.execution.manage", module: "yard", description: "Manage all workshops and planning" },
  { key: "yard.workshop.hull", module: "yard", description: "Hull workshop jobs only" },
  { key: "yard.workshop.steel", module: "yard", description: "Steel workshop jobs only" },
  { key: "yard.workshop.painting", module: "yard", description: "Painting workshop jobs only" },
  { key: "yard.workshop.machinery", module: "yard", description: "Machinery workshop jobs only" },
  { key: "yard.workshop.valve", module: "yard", description: "Valve / pipe workshop jobs only" },
  { key: "yard.workshop.electrical", module: "yard", description: "Electrical workshop jobs only" },
  { key: "yard.workshop.safety", module: "yard", description: "Safety / QA-QC inspections and permits" },
  { key: "yard.workshop.commercial", module: "yard", description: "Variations and invoice support" },
  { key: "yard.job.update", module: "yard", description: "Update workshop job progress" },
  { key: "yard.dependency.manage", module: "yard", description: "Manage job dependencies" },

  // —— Tender actions ——
  { key: "project.create", module: "tender", description: "Create tender project" },
  { key: "project.read", module: "tender", description: "View tender projects" },
  { key: "project.delete", module: "tender", description: "Delete tender project" },
  { key: "project.status.change", module: "tender", description: "Change project status" },
  { key: "spec.read", module: "tender", description: "View owner spec" },
  { key: "spec.edit", module: "tender", description: "Edit owner spec" },
  { key: "spec.import", module: "tender", description: "Import spec from Excel" },
  { key: "spec.lock", module: "tender", description: "Lock spec and issue tender" },
  { key: "category.read", module: "tender", description: "View cost categories" },
  { key: "category.edit", module: "tender", description: "Edit cost categories" },
  { key: "yard.invite", module: "tender", description: "Invite shipyards" },
  { key: "yard.revoke", module: "tender", description: "Revoke yard invites" },
  { key: "yard.view", module: "tender", description: "View yard invite status" },
  { key: "quote.read.summary", module: "tender", description: "View quote totals" },
  { key: "quote.read.detail", module: "tender", description: "View quote line detail" },
  { key: "quote.submit", module: "tender", description: "Submit yard quotation" },
  { key: "comparison.view", module: "tender", description: "View comparison matrix" },
  { key: "comparison.export", module: "tender", description: "Export comparison" },
  { key: "tender.shortlist", module: "tender", description: "Shortlist yard" },
  { key: "tender.award", module: "tender", description: "Award tender to yard" },

  // —— Organization ——
  { key: "org.user.manage", module: "org", description: "Manage company users" },
  { key: "org.role.manage", module: "org", description: "Manage roles and permissions" },
  { key: "org.profile.manage", module: "org", description: "Edit company profile" },

  // —— Sync / fleet ——
  { key: "sync.view_status", module: "sync", description: "View sync status" },
  { key: "device.register", module: "sync", description: "Register fleet device" },

  // —— Audit ——
  { key: "audit.read", module: "audit", description: "View audit log" },
];

export const PERMISSION_BY_KEY = Object.fromEntries(PERMISSIONS.map((p) => [p.key, p])) as Record<
  string,
  PermissionSeed
>;
