import type { SystemRoleSeed } from "@/lib/rbac/types";

/**
 * System role catalog — matches the RBAC spreadsheet (Role ID, Code, User Type, Hierarchy).
 * organizationId is null; companies clone or assign these templates via user_roles.
 */
export const SYSTEM_ROLES: SystemRoleSeed[] = [
  // Level 1 — System
  {
    roleNo: 1,
    code: "DEV_ADMIN",
    name: "Developer Admin",
    userType: "system",
    hierarchyLevel: 1,
    sortOrder: 1,
    designation: "Platform Administrator",
    department: "IT",
    description: "Owns entire platform",
  },
  // Level 2 — Company management
  {
    roleNo: 2,
    code: "COMP_ADMIN",
    name: "Company Admin",
    userType: "office",
    hierarchyLevel: 2,
    sortOrder: 2,
    designation: "Company Administrator",
    department: "Administration",
    description: "Company administration",
  },
  {
    roleNo: 3,
    code: "MD",
    name: "Managing Director",
    userType: "office",
    hierarchyLevel: 2,
    sortOrder: 3,
    designation: "Managing Director",
    department: "Management",
    description: "Executive",
  },
  {
    roleNo: 4,
    code: "TECH_DIR",
    name: "Technical Director",
    userType: "office",
    hierarchyLevel: 2,
    sortOrder: 4,
    designation: "Technical Director",
    department: "Technical",
    description: "Technical head",
  },
  // Level 3 — Department management
  {
    roleNo: 5,
    code: "FLEET_MGR",
    name: "Fleet Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 5,
    designation: "Fleet Manager",
    department: "Technical",
    description: "Fleet management",
  },
  {
    roleNo: 6,
    code: "TECH_MGR",
    name: "Technical Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 6,
    designation: "Technical Manager",
    department: "Technical",
    description: "Department head",
  },
  {
    roleNo: 7,
    code: "MARINE_MGR",
    name: "Marine Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 7,
    designation: "Marine Manager",
    department: "Marine",
    description: "Marine department",
  },
  {
    roleNo: 8,
    code: "HSEQ_MGR",
    name: "HSEQ Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 8,
    designation: "HSEQ Manager",
    department: "HSEQ",
    description: "HSEQ",
  },
  {
    roleNo: 9,
    code: "PUR_MGR",
    name: "Purchase Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 9,
    designation: "Purchase Manager",
    department: "Purchase",
    description: "Purchase approvals",
  },
  {
    roleNo: 10,
    code: "ACC_MGR",
    name: "Accounts Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 10,
    designation: "Accounts Manager",
    department: "Accounts",
    description: "Finance",
  },
  {
    roleNo: 11,
    code: "CREW_MGR",
    name: "Crewing Manager",
    userType: "office",
    hierarchyLevel: 3,
    sortOrder: 11,
    designation: "Crewing Manager",
    department: "Crewing",
    description: "Crew",
  },
  // Level 4 — Operations & support (office)
  {
    roleNo: 12,
    code: "TECH_SUPDT",
    name: "Technical Superintendent",
    userType: "office",
    hierarchyLevel: 4,
    sortOrder: 12,
    designation: "Technical Superintendent",
    department: "Technical",
    description: "Assigned vessels",
  },
  {
    roleNo: 13,
    code: "MAR_SUPDT",
    name: "Marine Superintendent",
    userType: "office",
    hierarchyLevel: 4,
    sortOrder: 13,
    designation: "Marine Superintendent",
    department: "Marine",
    description: "Assigned vessels",
  },
  {
    roleNo: 14,
    code: "PUR_OFF",
    name: "Purchase Officer",
    userType: "office",
    hierarchyLevel: 4,
    sortOrder: 14,
    designation: "Purchase Officer",
    department: "Purchase",
    description: "RFQ",
  },
  {
    roleNo: 15,
    code: "ACC_OFF",
    name: "Accounts Officer",
    userType: "office",
    hierarchyLevel: 4,
    sortOrder: 15,
    designation: "Accounts Officer",
    department: "Accounts",
    description: "Payments",
  },
  {
    roleNo: 16,
    code: "INV_CTRL",
    name: "Inventory Controller",
    userType: "office",
    hierarchyLevel: 4,
    sortOrder: 16,
    designation: "Inventory Controller",
    department: "Stores",
    description: "Inventory",
  },
  {
    roleNo: 17,
    code: "DOC_CTRL",
    name: "Document Controller",
    userType: "office",
    hierarchyLevel: 4,
    sortOrder: 17,
    designation: "Document Controller",
    department: "Documentation",
    description: "Documents",
  },
  // Level 5 — Vessel
  {
    roleNo: 18,
    code: "MASTER",
    name: "Master",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 18,
    designation: "Master",
    department: "Deck",
    description: "Master",
  },
  {
    roleNo: 19,
    code: "CENG",
    name: "Chief Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 19,
    designation: "Chief Engineer",
    department: "Engine",
    description: "Chief Engineer",
  },
  {
    roleNo: 20,
    code: "COFF",
    name: "Chief Officer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 20,
    designation: "Chief Officer",
    department: "Deck",
    description: "Chief Officer",
  },
  {
    roleNo: 21,
    code: "2ENG",
    name: "Second Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 21,
    designation: "Second Engineer",
    department: "Engine",
    description: "2/E",
  },
  {
    roleNo: 22,
    code: "ETO",
    name: "ETO",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 22,
    designation: "ETO",
    department: "Electrical",
    description: "ETO",
  },
  {
    roleNo: 23,
    code: "2OFF",
    name: "Second Officer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 23,
    designation: "Second Officer",
    department: "Deck",
    description: "2/O",
  },
  {
    roleNo: 24,
    code: "3OFF",
    name: "Third Officer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 24,
    designation: "Third Officer",
    department: "Deck",
    description: "3/O",
  },
  {
    roleNo: 25,
    code: "3ENG",
    name: "Third Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 25,
    designation: "Third Engineer",
    department: "Engine",
    description: "3/E",
  },
  {
    roleNo: 26,
    code: "4ENG",
    name: "Fourth Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    sortOrder: 26,
    designation: "Fourth Engineer",
    department: "Engine",
    description: "4/E",
  },
  // Level 6 — External
  {
    roleNo: 33,
    code: "SHIPYARD",
    name: "Shipyard User",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 33,
    designation: "Shipyard Coordinator",
    department: "Shipyard",
    description: "Dockyard",
  },
  {
    roleNo: 34,
    code: "VENDOR",
    name: "Vendor",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 34,
    designation: "Vendor Representative",
    department: "Vendor",
    description: "Supplier",
  },
  {
    roleNo: 35,
    code: "MAKER",
    name: "Maker Engineer",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 35,
    designation: "Maker Engineer",
    department: "Service",
    description: "OEM",
  },
  {
    roleNo: 36,
    code: "CLASS",
    name: "Class Surveyor",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 36,
    designation: "Class Surveyor",
    department: "Class",
    description: "Classification",
  },
  {
    roleNo: 37,
    code: "FLAG",
    name: "Flag Surveyor",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 37,
    designation: "Flag Surveyor",
    department: "Flag",
    description: "Flag State",
  },
  {
    roleNo: 38,
    code: "AUDITOR",
    name: "Auditor",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 38,
    designation: "External Auditor",
    department: "Audit",
    description: "Audit",
  },
  {
    roleNo: 39,
    code: "OWNER",
    name: "Owner Representative",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 39,
    designation: "Owner Representative",
    department: "Owner",
    description: "Owner Portal",
  },
  // Level 6 — Shipyard execution (workshop-scoped)
  {
    roleNo: 40,
    code: "YARD_PM",
    name: "Shipyard Project Manager",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 40,
    designation: "Project Manager",
    department: "Shipyard",
    description: "All workshops and planning",
  },
  {
    roleNo: 41,
    code: "YARD_PLAN",
    name: "Planning Engineer",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 41,
    designation: "Planning Engineer",
    department: "Shipyard Planning",
    description: "Timeline, dependencies, resources",
  },
  {
    roleNo: 42,
    code: "YARD_HULL",
    name: "Hull Workshop Manager",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 42,
    designation: "Hull Workshop Manager",
    department: "Hull Workshop",
    description: "Hull jobs only",
  },
  {
    roleNo: 43,
    code: "YARD_PAINT",
    name: "Paint Supervisor",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 43,
    designation: "Paint Supervisor",
    department: "Painting Workshop",
    description: "Painting jobs only",
  },
  {
    roleNo: 44,
    code: "YARD_MACH",
    name: "Machinery Supervisor",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 44,
    designation: "Machinery Supervisor",
    department: "Machinery Workshop",
    description: "Machinery jobs only",
  },
  {
    roleNo: 45,
    code: "YARD_QA",
    name: "QA-QC Inspector",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 45,
    designation: "QA-QC Inspector",
    department: "QA-QC",
    description: "Inspection and completion",
  },
  {
    roleNo: 46,
    code: "YARD_SAFETY",
    name: "Safety Officer",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 46,
    designation: "Safety Officer",
    department: "Safety",
    description: "Permits and safety",
  },
  {
    roleNo: 47,
    code: "YARD_COMM",
    name: "Commercial Officer",
    userType: "external",
    hierarchyLevel: 6,
    sortOrder: 47,
    designation: "Commercial Officer",
    department: "Commercial",
    description: "Variations and invoice",
  },
];

export const ROLE_BY_CODE = Object.fromEntries(SYSTEM_ROLES.map((r) => [r.code, r])) as Record<
  string,
  SystemRoleSeed
>;
