import type { SystemRoleSeed, RoleCategoryTier } from "@/lib/rbac/types";

/** Category tier derived from Role ID prefix (1000s = system, 2000s = company, …). */
export type { RoleCategoryTier } from "@/lib/rbac/types";

/**
 * Authoritative role catalog — matches Actinium-DD designation spreadsheet.
 * Role ID = roleNo (1001–6019). hierarchyLevel = tier (1–6). approvalLevel = sign-off authority (1–5).
 */
export const SYSTEM_ROLES: SystemRoleSeed[] = [
  // —— 1000s System ——
  {
    roleNo: 1001,
    code: "SYS_ADMIN",
    name: "System Administrator",
    userType: "system",
    hierarchyLevel: 1,
    categoryTier: "system",
    approvalLevel: 5,
    reportsToCode: null,
    sortOrder: 1001,
    designation: "Platform Administrator",
    department: "IT",
    jobScope:
      "Platform configuration, licensing, security, backups, user & role management, global settings, integrations.",
  },
  {
    roleNo: 1002,
    code: "SYS_OFF",
    name: "System Officer",
    userType: "system",
    hierarchyLevel: 1,
    categoryTier: "system",
    approvalLevel: 4,
    reportsToCode: "SYS_ADMIN",
    sortOrder: 1002,
    designation: "Platform Officer",
    department: "IT",
    jobScope:
      "Company onboarding, module activation, master data, support coordination, subscription administration.",
  },
  {
    roleNo: 1003,
    code: "SYS_OPERATOR",
    name: "System Operator",
    userType: "system",
    hierarchyLevel: 1,
    categoryTier: "system",
    approvalLevel: 2,
    reportsToCode: "SYS_OFF",
    sortOrder: 1003,
    designation: "Platform Operator",
    department: "IT",
    jobScope:
      "Daily operations, sync jobs, email queues, scheduler, imports, exports, operational support.",
  },
  {
    roleNo: 1004,
    code: "SYS_MONITOR",
    name: "System Monitoring Officer",
    userType: "system",
    hierarchyLevel: 1,
    categoryTier: "system",
    approvalLevel: 2,
    reportsToCode: "SYS_OFF",
    sortOrder: 1004,
    designation: "System Monitoring Officer",
    department: "IT",
    jobScope:
      "Infrastructure, database, API, sync engine, performance, alerts, uptime, audit monitoring.",
  },

  // —— 2000s Company ——
  {
    roleNo: 2001,
    code: "COMP_ADMIN",
    name: "Company Administrator",
    userType: "office",
    hierarchyLevel: 2,
    categoryTier: "company",
    approvalLevel: 5,
    reportsToCode: "SYS_OFF",
    sortOrder: 2001,
    designation: "Company Administrator",
    department: "Administration",
    jobScope:
      "Company configuration, departments, vessels, users, permissions, company masters.",
  },
  {
    roleNo: 2002,
    code: "MD",
    name: "Managing Director",
    userType: "office",
    hierarchyLevel: 2,
    categoryTier: "company",
    approvalLevel: 5,
    reportsToCode: "COMP_ADMIN",
    sortOrder: 2002,
    designation: "Managing Director",
    department: "Management",
    jobScope: "Final approvals, budgets, strategy, management review.",
  },
  {
    roleNo: 2003,
    code: "TECH_DIR",
    name: "Technical Director",
    userType: "office",
    hierarchyLevel: 2,
    categoryTier: "company",
    approvalLevel: 5,
    reportsToCode: "MD",
    sortOrder: 2003,
    designation: "Technical Director",
    department: "Technical",
    jobScope: "Technical policy, fleet strategy, dry dock approvals.",
  },

  // —— 3000s Department ——
  {
    roleNo: 3001,
    code: "FLEET_MGR",
    name: "Fleet Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "TECH_DIR",
    sortOrder: 3001,
    designation: "Fleet Manager",
    department: "Technical",
    jobScope: "Fleet performance, KPI monitoring, superintendent allocation.",
  },
  {
    roleNo: 3002,
    code: "TECH_MGR",
    name: "Technical Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "TECH_DIR",
    sortOrder: 3002,
    designation: "Technical Manager",
    department: "Technical",
    jobScope: "Manage technical superintendents, budgets, dry dock planning.",
  },
  {
    roleNo: 3003,
    code: "MARINE_MGR",
    name: "Marine Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "TECH_DIR",
    sortOrder: 3003,
    designation: "Marine Manager",
    department: "Marine",
    jobScope: "Marine operations, navigation, vetting, PSC oversight.",
  },
  {
    roleNo: 3004,
    code: "HSEQ_MGR",
    name: "HSEQ Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "MD",
    sortOrder: 3004,
    designation: "HSEQ Manager",
    department: "HSEQ",
    jobScope: "ISM, ISPS, ISO, audits, incidents.",
  },
  {
    roleNo: 3005,
    code: "PUR_MGR",
    name: "Purchase Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "MD",
    sortOrder: 3005,
    designation: "Purchase Manager",
    department: "Purchase",
    jobScope: "Procurement strategy, vendor approval.",
  },
  {
    roleNo: 3006,
    code: "ACC_MGR",
    name: "Accounts Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "MD",
    sortOrder: 3006,
    designation: "Accounts Manager",
    department: "Accounts",
    jobScope: "Financial control, invoices, budgets.",
  },
  {
    roleNo: 3007,
    code: "CREW_MGR",
    name: "Crewing Manager",
    userType: "office",
    hierarchyLevel: 3,
    categoryTier: "department",
    approvalLevel: 4,
    reportsToCode: "MD",
    sortOrder: 3007,
    designation: "Crewing Manager",
    department: "Crewing",
    jobScope: "Crewing, certification, manpower.",
  },

  // —— 4000s Office operations ——
  {
    roleNo: 4001,
    code: "TECH_SUPDT",
    name: "Technical Superintendent",
    userType: "office",
    hierarchyLevel: 4,
    categoryTier: "office",
    approvalLevel: 3,
    reportsToCode: "TECH_MGR",
    sortOrder: 4001,
    designation: "Technical Superintendent",
    department: "Technical",
    jobScope:
      "Dry dock planning, PMS, defects, budgets, class coordination, project execution.",
  },
  {
    roleNo: 4002,
    code: "MAR_SUPDT",
    name: "Marine Superintendent",
    userType: "office",
    hierarchyLevel: 4,
    categoryTier: "office",
    approvalLevel: 3,
    reportsToCode: "MARINE_MGR",
    sortOrder: 4002,
    designation: "Marine Superintendent",
    department: "Marine",
    jobScope: "Navigation, cargo, PSC, marine compliance.",
  },
  {
    roleNo: 4003,
    code: "PUR_OFF",
    name: "Purchase Officer",
    userType: "office",
    hierarchyLevel: 4,
    categoryTier: "office",
    approvalLevel: 2,
    reportsToCode: "PUR_MGR",
    sortOrder: 4003,
    designation: "Purchase Officer",
    department: "Purchase",
    jobScope: "RFQs, quotations, purchase orders, delivery tracking.",
  },
  {
    roleNo: 4004,
    code: "ACC_OFF",
    name: "Accounts Officer",
    userType: "office",
    hierarchyLevel: 4,
    categoryTier: "office",
    approvalLevel: 2,
    reportsToCode: "ACC_MGR",
    sortOrder: 4004,
    designation: "Accounts Officer",
    department: "Accounts",
    jobScope: "Invoice verification, payment processing.",
  },
  {
    roleNo: 4005,
    code: "INV_CTRL",
    name: "Inventory Controller",
    userType: "office",
    hierarchyLevel: 4,
    categoryTier: "office",
    approvalLevel: 2,
    reportsToCode: "PUR_MGR",
    sortOrder: 4005,
    designation: "Inventory Controller",
    department: "Stores",
    jobScope: "Inventory, spares, stores, stock accuracy.",
  },
  {
    roleNo: 4006,
    code: "DOC_CTRL",
    name: "Document Controller",
    userType: "office",
    hierarchyLevel: 4,
    categoryTier: "office",
    approvalLevel: 2,
    reportsToCode: "COMP_ADMIN",
    sortOrder: 4006,
    designation: "Document Controller",
    department: "Documentation",
    jobScope: "Document control, revisions, certificates.",
  },

  // —— 5000s Vessel ——
  {
    roleNo: 5001,
    code: "MASTER",
    name: "Master",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 3,
    reportsToCode: "TECH_SUPDT",
    sortOrder: 5001,
    designation: "Master",
    department: "Deck",
    jobScope: "Overall vessel command, approvals, operational reporting.",
  },
  {
    roleNo: 5002,
    code: "CENG",
    name: "Chief Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 3,
    reportsToCode: "TECH_SUPDT",
    sortOrder: 5002,
    designation: "Chief Engineer",
    department: "Engine",
    jobScope: "Engine department, machinery condition, dry dock inputs.",
  },
  {
    roleNo: 5003,
    code: "COFF",
    name: "Chief Officer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 3,
    reportsToCode: "MAR_SUPDT",
    sortOrder: 5003,
    designation: "Chief Officer",
    department: "Deck",
    jobScope: "Deck maintenance, cargo, hull condition.",
  },
  {
    roleNo: 5004,
    code: "2ENG",
    name: "Second Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 2,
    reportsToCode: "CENG",
    sortOrder: 5004,
    designation: "Second Engineer",
    department: "Engine",
    jobScope: "Execute engineering maintenance and dry dock jobs.",
  },
  {
    roleNo: 5005,
    code: "ETO",
    name: "ETO",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 2,
    reportsToCode: "CENG",
    sortOrder: 5005,
    designation: "Electro Technical Officer",
    department: "Electrical",
    jobScope: "Electrical and automation systems.",
  },
  {
    roleNo: 5006,
    code: "2OFF",
    name: "Second Officer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 2,
    reportsToCode: "MASTER",
    sortOrder: 5006,
    designation: "Second Officer",
    department: "Deck",
    jobScope: "Navigation publications, safety equipment.",
  },
  {
    roleNo: 5007,
    code: "3OFF",
    name: "Third Officer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 1,
    reportsToCode: "MASTER",
    sortOrder: 5007,
    designation: "Third Officer",
    department: "Deck",
    jobScope: "LSA/FFA maintenance.",
  },
  {
    roleNo: 5008,
    code: "3ENG",
    name: "Third Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 1,
    reportsToCode: "CENG",
    sortOrder: 5008,
    designation: "Third Engineer",
    department: "Engine",
    jobScope: "Auxiliary machinery maintenance.",
  },
  {
    roleNo: 5009,
    code: "4ENG",
    name: "Fourth Engineer",
    userType: "vessel",
    hierarchyLevel: 5,
    categoryTier: "vessel",
    approvalLevel: 1,
    reportsToCode: "CENG",
    sortOrder: 5009,
    designation: "Fourth Engineer",
    department: "Engine",
    jobScope: "Routine machinery maintenance.",
  },

  // —— 6000s External (shipyard workshop + third parties) ——
  {
    roleNo: 6001,
    code: "YARD_PM",
    name: "Shipyard Project Manager",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 2,
    reportsToCode: "TECH_SUPDT",
    sortOrder: 6001,
    designation: "Project Manager",
    department: "Shipyard",
    jobScope: "Overall shipyard project execution.",
  },
  {
    roleNo: 6002,
    code: "YARD_PLAN",
    name: "Planning Engineer",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6002,
    designation: "Planning Engineer",
    department: "Shipyard Planning",
    jobScope: "Planning, scheduling, milestones.",
  },
  {
    roleNo: 6003,
    code: "YARD_HULL",
    name: "Hull Workshop Manager",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6003,
    designation: "Hull Workshop Manager",
    department: "Hull Workshop",
    jobScope: "Hull repairs and inspections.",
  },
  {
    roleNo: 6004,
    code: "YARD_STEEL",
    name: "Steel Workshop Manager",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6004,
    designation: "Steel Workshop Manager",
    department: "Steel Workshop",
    jobScope: "Steel renewal and fabrication.",
  },
  {
    roleNo: 6005,
    code: "YARD_PAINT",
    name: "Paint Supervisor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6005,
    designation: "Paint Supervisor",
    department: "Painting Workshop",
    jobScope: "Blasting, coating, DFT control.",
  },
  {
    roleNo: 6006,
    code: "YARD_MACH",
    name: "Machinery Supervisor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6006,
    designation: "Machinery Supervisor",
    department: "Machinery Workshop",
    jobScope: "Machinery overhaul.",
  },
  {
    roleNo: 6007,
    code: "YARD_ELEC",
    name: "Electrical Supervisor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6007,
    designation: "Electrical Supervisor",
    department: "Electrical Workshop",
    jobScope: "Electrical repairs and testing.",
  },
  {
    roleNo: 6008,
    code: "YARD_PIPE",
    name: "Pipe Workshop Supervisor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6008,
    designation: "Pipe Workshop Supervisor",
    department: "Pipe Workshop",
    jobScope: "Pipe fabrication and pressure testing.",
  },
  {
    roleNo: 6009,
    code: "YARD_QA",
    name: "QA/QC Inspector",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6009,
    designation: "QA/QC Inspector",
    department: "QA-QC",
    jobScope: "Inspection, QA/QC records.",
  },
  {
    roleNo: 6010,
    code: "YARD_SAFETY",
    name: "Safety Officer",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6010,
    designation: "Safety Officer",
    department: "Safety",
    jobScope: "Permits, safety compliance.",
  },
  {
    roleNo: 6011,
    code: "YARD_COMM",
    name: "Commercial Officer",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_PM",
    sortOrder: 6011,
    designation: "Commercial Officer",
    department: "Commercial",
    jobScope: "Commercial, variation orders, invoices.",
  },
  {
    roleNo: 6012,
    code: "VENDOR",
    name: "Vendor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_COMM",
    sortOrder: 6012,
    designation: "Vendor Representative",
    department: "Vendor",
    jobScope: "Supply goods/services.",
  },
  {
    roleNo: 6013,
    code: "SERVICE_VENDOR",
    name: "Service Vendor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "YARD_COMM",
    sortOrder: 6013,
    designation: "Service Provider",
    department: "Vendor",
    jobScope: "Execute specialist services.",
  },
  {
    roleNo: 6014,
    code: "MAKER",
    name: "Maker Engineer",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 1,
    reportsToCode: "TECH_SUPDT",
    sortOrder: 6014,
    designation: "Maker Engineer",
    department: "Service",
    jobScope: "OEM attendance and commissioning.",
  },
  {
    roleNo: 6015,
    code: "CLASS",
    name: "Classification Society",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 2,
    reportsToCode: "TECH_SUPDT",
    sortOrder: 6015,
    designation: "Class Surveyor",
    department: "Class",
    jobScope: "Survey, certification, statutory approvals.",
  },
  {
    roleNo: 6016,
    code: "FLAG",
    name: "Flag Administration",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 2,
    reportsToCode: "TECH_SUPDT",
    sortOrder: 6016,
    designation: "Flag State Surveyor",
    department: "Flag",
    jobScope: "Flag inspections and approvals.",
  },
  {
    roleNo: 6017,
    code: "OWNER",
    name: "Owner Representative",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 3,
    reportsToCode: "MD",
    sortOrder: 6017,
    designation: "Owner Representative",
    department: "Owner",
    jobScope: "Commercial/technical owner decisions.",
  },
  {
    roleNo: 6018,
    code: "OWNER_SUPDT",
    name: "Owner Superintendent",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 2,
    reportsToCode: "OWNER",
    sortOrder: 6018,
    designation: "Owner Technical Representative",
    department: "Owner",
    jobScope: "Owner-side technical supervision.",
  },
  {
    roleNo: 6019,
    code: "AUDITOR",
    name: "External Auditor",
    userType: "external",
    hierarchyLevel: 6,
    categoryTier: "external",
    approvalLevel: 2,
    reportsToCode: "COMP_ADMIN",
    sortOrder: 6019,
    designation: "External Auditor",
    department: "Audit",
    jobScope: "External audits and compliance verification.",
  },
];

/** @deprecated Renamed to SYS_ADMIN — kept for migration lookups. */
export const LEGACY_ROLE_CODE_ALIASES: Record<string, string> = {
  DEV_ADMIN: "SYS_ADMIN",
  SHIPYARD: "YARD_PM",
};

export const ROLE_BY_CODE = Object.fromEntries(SYSTEM_ROLES.map((r) => [r.code, r])) as Record<
  string,
  SystemRoleSeed
>;

export const ROLE_CATEGORY_TIER_LABELS: Record<RoleCategoryTier, string> = {
  system: "System (1000s)",
  company: "Company (2000s)",
  department: "Department (3000s)",
  office: "Office (4000s)",
  vessel: "Vessel (5000s)",
  external: "External (6000s)",
};
