/**
 * Default permission bundles per system role (tender module + pages).
 * Companies can override via role_permissions on cloned roles later.
 */
import { SUPERINTENDENT_PAGE_KEYS } from "@/lib/rbac/superintendentPages";

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  SYS_ADMIN: ["*"],
  /** @deprecated alias — migrated to SYS_ADMIN */
  DEV_ADMIN: ["*"],

  SYS_OFF: [
    "page.office.admin",
    "page.office.admin.companies",
    "page.office.admin.vessels",
    "page.office.admin.employees",
    "page.office.admin.shipyards",
    "page.office.admin.externalVendors",
    "page.office.admin.roles",
    "page.office.admin.access",
    "org.user.manage",
    "org.role.manage",
    "org.profile.manage",
    "platform.config.manage",
    "sync.view_status",
    "audit.read",
  ],
  SYS_OPERATOR: ["sync.view_status", "audit.read", "page.platform.operator"],
  SYS_MONITOR: ["sync.view_status", "audit.read", "platform.config.manage", "page.platform.monitor"],

  COMP_ADMIN: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.office.admin.users",
    "page.office.admin.companies",
    "page.office.admin.vessels",
    "page.office.admin.employees",
    "page.office.admin.crewCredentials",
    "page.office.admin.shipyards",
    "page.office.admin.externalVendors",
    "page.office.admin.roles",
    "page.office.admin",
    "page.office.admin.access",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "project.delete",
    "project.status.change",
    "spec.read",
    "spec.edit",
    "spec.import",
    "spec.lock",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.revoke",
    "yard.view",
    "quote.read.summary",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "org.user.manage",
    "org.role.manage",
    "org.profile.manage",
    "sync.view_status",
    "device.register",
    "audit.read",
  ],

  MD: [
    "page.office.projects",
    "page.office.project.overview",
    "page.office.project.comparison",
    "page.office.department.executive",
    "page.superintendent.approvals",
    "project.read",
    "quote.read.summary",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "audit.read",
  ],

  TECH_DIR: [
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.office.department.executive",
    "page.superintendent.approvals",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "project.status.change",
    "spec.read",
    "spec.edit",
    "spec.lock",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "sync.view_status",
  ],

  FLEET_MGR: [
    "page.office.projects",
    "page.office.project.overview",
    "page.office.project.comparison",
    "page.office.department.fleet",
    "page.desktop.jobs",
    "project.read",
    "comparison.view",
    "comparison.export",
    "quote.read.summary",
  ],

  TECH_MGR: [
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.superintendent.approvals",
    ...SUPERINTENDENT_PAGE_KEYS,
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "project.status.change",
    "spec.read",
    "spec.edit",
    "spec.import",
    "spec.lock",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.revoke",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "sync.view_status",
  ],

  MARINE_MGR: [
    "page.office.projects",
    "page.office.project.overview",
    "project.read",
    "spec.read",
    "comparison.view",
  ],

  HSEQ_MGR: [
    "page.office.projects",
    "page.office.project.overview",
    "page.office.department.hseq",
    "project.read",
    "audit.read",
  ],

  PUR_MGR: [
    "page.office.projects",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.office.procurement",
    "page.purchase",
    "page.purchase.dashboard",
    "page.purchase.requisitions",
    "page.purchase.orders",
    "page.purchase.invoices",
    "page.purchase.vendors",
    "page.purchase.budget",
    "page.superintendent.procurement",
    "page.superintendent.vesselRequisitions",
    "project.read",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
  ],

  ACC_MGR: [
    "page.office.projects",
    "page.office.project.comparison",
    "page.office.accounts",
    "page.purchase",
    "page.purchase.dashboard",
    "page.purchase.orders",
    "page.purchase.invoices",
    "page.purchase.budget",
    "page.superintendent.budget",
    "page.superintendent.approvals",
    "project.read",
    "quote.read.summary",
    "comparison.view",
    "comparison.export",
  ],

  CREW_MGR: [
    "page.office.projects",
    "page.office.department.crewing",
    "page.office.admin.crewCredentials",
    "project.read",
  ],

  TECH_SUPDT: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    ...SUPERINTENDENT_PAGE_KEYS,
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "spec.read",
    "spec.edit",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "sync.view_status",
    "device.register",
  ],

  MAR_SUPDT: [
    "page.office.projects",
    "page.office.project.overview",
    "page.superintendent.dashboard",
    "page.superintendent.projects",
    "page.superintendent.projectWorkspace",
    "page.superintendent.monitoring",
    "page.desktop.jobs",
    "project.read",
    "spec.read",
    "comparison.view",
    "sync.view_status",
    "device.register",
  ],

  PUR_OFF: [
    "page.office.projects",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.office.procurement",
    "page.superintendent.procurement",
    "page.superintendent.vesselRequisitions",
    "project.read",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
  ],

  ACC_OFF: [
    "page.office.projects",
    "page.office.project.comparison",
    "page.office.accounts",
    "page.superintendent.budget",
    "project.read",
    "quote.read.summary",
    "comparison.view",
  ],

  INV_CTRL: [
    "page.office.projects",
    "page.superintendent.spares",
    "page.superintendent.vesselRequisitions",
    "project.read",
  ],
  DOC_CTRL: [
    "page.office.projects",
    "page.superintendent.documents",
    "project.read",
    "spec.read",
  ],

  MASTER: [
    "page.shipAccess.dashboard",
    "page.shipAccess.machineryDashboard",
    "page.shipAccess.dryDockDashboard",
    "page.shipAccess.dryDockJobs",
    "page.shipAccess.dryDockJobs.masterReview",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "page.shipAccess.defects",
    "page.shipAccess.defects.new",
    "page.shipAccess.defects.edit",
    "page.shipAccess.defects.masterReview",
    "page.shipAccess.purchase",
    "page.shipAccess.purchase.new",
    "page.shipAccess.purchase.edit",
    "page.shipAccess.purchase.masterReview",
    "ship.job.create",
    "ship.job.read",
    "ship.job.masterApprove",
    "ship.defect.create",
    "ship.defect.read",
    "ship.defect.update",
    "ship.defect.masterApprove",
    "ship.purchase.read",
    "ship.purchase.create",
    "ship.purchase.update",
    "ship.purchase.masterApprove",
    "page.desktop.jobs",
    "project.read",
    "spec.read",
    "comparison.view",
    "sync.view_status",
  ],
  CENG: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "page.shipAccess.machineryDashboard",
    "page.shipAccess.machineryRunningHours",
    "page.shipAccess.machineryParameters",
    "page.shipAccess.machineryCondition",
    "page.shipAccess.pms",
    "page.shipAccess.defects",
    "page.shipAccess.defects.new",
    "page.shipAccess.purchase",
    "page.shipAccess.purchase.new",
    "page.shipAccess.purchase.edit",
    "ship.job.create",
    "ship.job.read",
    "ship.defect.create",
    "ship.defect.read",
    "ship.defect.update",
    "ship.purchase.read",
    "ship.purchase.create",
    "ship.purchase.update",
    "page.desktop.jobs",
    "project.read",
    "spec.read",
    "comparison.view",
    "sync.view_status",
  ],
  COFF: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "page.shipAccess.pms",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
    "comparison.view",
  ],
  "2ENG": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "page.shipAccess.machineryDashboard",
    "page.shipAccess.machineryRunningHours",
    "page.shipAccess.pms",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
    "comparison.view",
  ],
  ETO: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "2OFF": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "3OFF": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "3ENG": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "4ENG": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],

  SHIPYARD: [
    "page.yard.quote",
    "page.shipyard.dashboard",
    "page.shipyard.projects",
    "page.shipyard.workshops",
    "page.shipyard.planning",
    "page.shipyard.execution",
    "page.shipyard.commercial",
    "page.shipyard.tender",
    "quote.submit",
    "spec.read",
    "yard.execution.read",
    "yard.execution.manage",
    "yard.job.update",
    "yard.dependency.manage",
  ],
  YARD_PM: [
    "page.shipyard.dashboard",
    "page.shipyard.projects",
    "page.shipyard.workshops",
    "page.shipyard.planning",
    "page.shipyard.execution",
    "page.shipyard.commercial",
    "page.shipyard.tender",
    "yard.execution.read",
    "yard.execution.manage",
    "yard.job.update",
    "yard.dependency.manage",
    "spec.read",
  ],
  YARD_PLAN: [
    "page.shipyard.dashboard",
    "page.shipyard.projects",
    "page.shipyard.planning",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.dependency.manage",
    "yard.job.update",
    "spec.read",
  ],
  YARD_HULL: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.hull",
    "yard.job.update",
  ],
  YARD_PAINT: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.painting",
    "yard.job.update",
  ],
  YARD_MACH: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.machinery",
    "yard.job.update",
  ],
  YARD_QA: [
    "page.shipyard.execution",
    "page.shipyard.commercial",
    "yard.execution.read",
    "yard.workshop.safety",
    "yard.job.update",
  ],
  YARD_SAFETY: [
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.safety",
    "yard.job.update",
  ],
  YARD_COMM: [
    "page.shipyard.commercial",
    "page.shipyard.tender",
    "yard.execution.read",
    "yard.workshop.commercial",
    "spec.read",
  ],
  VENDOR: ["page.external.portal", "page.yard.quote", "quote.read.summary", "quote.submit"],
  MAKER: ["page.external.portal"],
  CLASS: ["page.external.class", "page.office.projects", "project.read", "spec.read"],
  FLAG: ["page.external.flag", "page.office.projects", "project.read", "spec.read"],
  AUDITOR: ["page.external.auditor", "page.office.projects", "project.read", "audit.read"],
  OWNER: [
    "page.external.owner",
    "page.office.projects",
    "project.read",
    "quote.read.summary",
    "comparison.view",
  ],
  OWNER_SUPDT: [
    "page.external.owner",
    "page.office.projects",
    "project.read",
    "spec.read",
    "comparison.view",
  ],
  SERVICE_VENDOR: ["page.external.portal", "quote.read.summary", "quote.submit"],
  YARD_STEEL: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.steel",
    "yard.job.update",
  ],
  YARD_ELEC: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.electrical",
    "yard.job.update",
  ],
  YARD_PIPE: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.valve",
    "yard.job.update",
  ],
};

/** Expand DEV_ADMIN wildcard to all permission keys at seed time. */
export function resolveRolePermissionKeys(
  roleCode: string,
  allPermissionKeys: string[],
): string[] {
  const keys = DEFAULT_ROLE_PERMISSIONS[roleCode];
  if (!keys) return [];
  if (keys.includes("*")) return allPermissionKeys;
  return keys;
}

/** Map Next.js path patterns to page permission keys. */
export const PAGE_ROUTE_PERMISSIONS: { pattern: RegExp; permission: string }[] = [
  { pattern: /^\/projects\/new\/?$/, permission: "page.office.projects.new" },
  { pattern: /^\/projects\/?$/, permission: "page.office.projects" },
  { pattern: /^\/projects\/[^/]+\/?$/, permission: "page.office.project.overview" },
  { pattern: /^\/quote\/[^/]+\/?$/, permission: "page.yard.quote" },
  { pattern: /^\/platform\/monitor\/?$/, permission: "page.platform.monitor" },
  { pattern: /^\/platform\/operator\/?$/, permission: "page.platform.operator" },
  { pattern: /^\/platform\/?$/, permission: "page.platform.admin" },
  { pattern: /^\/office\/executive\/?$/, permission: "page.office.department.executive" },
  { pattern: /^\/office\/fleet\/?$/, permission: "page.office.department.fleet" },
  { pattern: /^\/office\/hseq\/?$/, permission: "page.office.department.hseq" },
  { pattern: /^\/office\/crewing\/?$/, permission: "page.office.department.crewing" },
  { pattern: /^\/office\/procurement\/?$/, permission: "page.office.procurement" },
  { pattern: /^\/office\/accounts\/?$/, permission: "page.office.accounts" },
  { pattern: /^\/purchase\/dashboard(\/.*)?$/, permission: "page.purchase.dashboard" },
  { pattern: /^\/purchase\/(create-requisition|draft-requisitions|view-requisitions|requisitions)(\/.*)?$/, permission: "page.purchase.requisitions" },
  { pattern: /^\/purchase\/(purchase-orders|create-po|view-pos|po-budget-change|po-variance|dn-status)(\/.*)?$/, permission: "page.purchase.orders" },
  { pattern: /^\/purchase\/(invoices|credit-notes|invoicer-payer)(\/.*)?$/, permission: "page.purchase.invoices" },
  { pattern: /^\/purchase\/(vendor-management|vendors)(\/.*)?$/, permission: "page.purchase.vendors" },
  { pattern: /^\/purchase\/(budget-control)(\/.*)?$/, permission: "page.purchase.budget" },
  { pattern: /^\/purchase(\/.*)?$/, permission: "page.purchase" },
  { pattern: /^\/external\/class(\/.*)?$/, permission: "page.external.class" },
  { pattern: /^\/external\/flag(\/.*)?$/, permission: "page.external.flag" },
  { pattern: /^\/external\/owner(\/.*)?$/, permission: "page.external.owner" },
  { pattern: /^\/external\/auditor(\/.*)?$/, permission: "page.external.auditor" },
  { pattern: /^\/external(\/.*)?$/, permission: "page.external.portal" },
  { pattern: /^\/superintendent\/projects\/[^/]+\/procurement(\/.*)?$/, permission: "page.superintendent.procurement" },
  { pattern: /^\/superintendent\/projects\/[^/]+\/documents(\/.*)?$/, permission: "page.superintendent.documents" },
  { pattern: /^\/superintendent\/projects\/[^/]+\/closeout(\/.*)?$/, permission: "page.superintendent.closeout" },
  { pattern: /^\/superintendent\/projects\/[^/]+(\/.*)?$/, permission: "page.superintendent.projectWorkspace" },
  { pattern: /^\/superintendent\/projects(\/.*)?$/, permission: "page.superintendent.projects" },
  { pattern: /^\/superintendent\/budget(\/.*)?$/, permission: "page.superintendent.budget" },
  { pattern: /^\/superintendent\/monitoring(\/.*)?$/, permission: "page.superintendent.monitoring" },
  { pattern: /^\/superintendent\/spares(\/.*)?$/, permission: "page.superintendent.spares" },
  { pattern: /^\/superintendent\/approvals(\/.*)?$/, permission: "page.superintendent.approvals" },
  { pattern: /^\/superintendent\/vessel-requisitions(\/.*)?$/, permission: "page.superintendent.vesselRequisitions" },
  { pattern: /^\/superintendent\/vessel-jobs(\/.*)?$/, permission: "page.superintendent.vesselJobs" },
  { pattern: /^\/superintendent\/planning(\/.*)?$/, permission: "page.superintendent.planning" },
  { pattern: /^\/superintendent\/jobs(\/.*)?$/, permission: "page.superintendent.jobs" },
  { pattern: /^\/superintendent\/vessels(\/.*)?$/, permission: "page.superintendent.vessels" },
  { pattern: /^\/superintendent(\/.*)?$/, permission: "page.superintendent.dashboard" },
  { pattern: /^\/ship-access\/pms(\/.*)?$/, permission: "page.shipAccess.pms" },
  { pattern: /^\/ship-access\/machinery\/running-hours(\/.*)?$/, permission: "page.shipAccess.machineryRunningHours" },
  { pattern: /^\/ship-access\/machinery\/parameters(\/.*)?$/, permission: "page.shipAccess.machineryParameters" },
  { pattern: /^\/ship-access\/machinery\/condition(\/.*)?$/, permission: "page.shipAccess.machineryCondition" },
  { pattern: /^\/ship-access\/machinery(\/.*)?$/, permission: "page.shipAccess.machineryDashboard" },
  { pattern: /^\/ship-access\/dry-dock\/jobs\/new\/?$/, permission: "page.shipAccess.dryDockJobs.new" },
  { pattern: /^\/ship-access\/dry-dock\/jobs(\/.*)?$/, permission: "page.shipAccess.dryDockJobs" },
  { pattern: /^\/ship-access\/dry-dock(\/.*)?$/, permission: "page.shipAccess.dryDockDashboard" },
  { pattern: /^\/ship-access\/machinery-hours\/?$/, permission: "page.shipAccess.machineryHours" },
  { pattern: /^\/ship-access\/purchase\/new\/?$/, permission: "page.shipAccess.purchase.new" },
  { pattern: /^\/ship-access\/purchase\/[^/]+\/edit\/?$/, permission: "page.shipAccess.purchase.edit" },
  { pattern: /^\/ship-access\/purchase\/?$/, permission: "page.shipAccess.purchase" },
  { pattern: /^\/ship-access\/defects\/new\/?$/, permission: "page.shipAccess.defects.new" },
  { pattern: /^\/ship-access\/defects\/[^/]+\/edit\/?$/, permission: "page.shipAccess.defects.edit" },
  { pattern: /^\/ship-access\/defects\/?$/, permission: "page.shipAccess.defects" },
  { pattern: /^\/ship-access\/jobs\/new\/?$/, permission: "page.shipAccess.jobs.new" },
  { pattern: /^\/ship-access\/jobs\/[^/]+\/edit\/?$/, permission: "page.shipAccess.jobs.edit" },
  { pattern: /^\/ship-access\/jobs\/?$/, permission: "page.shipAccess.jobs" },
  { pattern: /^\/ship-access\/?$/, permission: "page.shipAccess.dashboard" },
  { pattern: /^\/shipyard\/?$/, permission: "page.shipyard.dashboard" },
  { pattern: /^\/shipyard\/projects(\/.*)?$/, permission: "page.shipyard.projects" },
  { pattern: /^\/shipyard\/workshops(\/.*)?$/, permission: "page.shipyard.workshops" },
  { pattern: /^\/shipyard\/planning(\/.*)?$/, permission: "page.shipyard.planning" },
  { pattern: /^\/shipyard\/execution(\/.*)?$/, permission: "page.shipyard.execution" },
  { pattern: /^\/shipyard\/(commercial|tender|yards)(\/.*)?$/, permission: "page.shipyard.commercial" },
  { pattern: /^\/admin\/companies(\/.*)?$/, permission: "page.office.admin.companies" },
  { pattern: /^\/admin\/shipyards(\/.*)?$/, permission: "page.office.admin.shipyards" },
  { pattern: /^\/admin\/external-vendors(\/.*)?$/, permission: "page.office.admin.externalVendors" },
  { pattern: /^\/admin\/vessels(\/.*)?$/, permission: "page.office.admin.vessels" },
  { pattern: /^\/admin\/employees(\/.*)?$/, permission: "page.office.admin.employees" },
  { pattern: /^\/admin\/crew-credentials(\/.*)?$/, permission: "page.office.admin.crewCredentials" },
  { pattern: /^\/admin\/access\/?$/, permission: "page.office.admin.access" },
  { pattern: /^\/admin\/users\/?$/, permission: "page.office.admin.users" },
  { pattern: /^\/admin\/roles\/?$/, permission: "page.office.admin.roles" },
  { pattern: /^\/admin\/?$/, permission: "page.office.admin" },
];

export function pagePermissionForPath(pathname: string): string | null {
  for (const { pattern, permission } of PAGE_ROUTE_PERMISSIONS) {
    if (pattern.test(pathname)) return permission;
  }
  return null;
}

/** Project dashboard tab → page permission. */
export const PROJECT_TAB_PERMISSIONS: Record<string, string> = {
  overview: "page.office.project.overview",
  categories: "page.office.project.categories",
  spec: "page.office.project.spec",
  yards: "page.office.project.yards",
  comparison: "page.office.project.comparison",
};
