/**
 * Default permission bundles per system role (tender module + pages).
 * Companies can override via role_permissions on cloned roles later.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  DEV_ADMIN: ["*"],

  COMP_ADMIN: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.office.admin.users",
    "page.office.admin.companies",
    "page.office.admin.vessels",
    "page.office.admin.employees",
    "page.office.admin.roles",
    "page.office.admin",
    "page.office.admin.access",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "project.delete",
    "project.status.change",
    "spec.read",
    "spec.edit",
    "spec.import",
    "spec.lock",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.revoke",
    "yard.view",
    "quote.read.summary",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "org.user.manage",
    "org.role.manage",
    "org.profile.manage",
    "sync.view_status",
    "device.register",
    "audit.read",
  ],

  MD: [
    "page.office.projects",
    "page.office.project.overview",
    "page.office.project.comparison",
    "project.read",
    "quote.read.summary",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "audit.read",
  ],

  TECH_DIR: [
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "project.status.change",
    "spec.read",
    "spec.edit",
    "spec.lock",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "sync.view_status",
  ],

  FLEET_MGR: [
    "page.office.projects",
    "page.office.project.overview",
    "page.office.project.comparison",
    "page.desktop.jobs",
    "project.read",
    "comparison.view",
    "comparison.export",
    "quote.read.summary",
  ],

  TECH_MGR: [
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "project.status.change",
    "spec.read",
    "spec.edit",
    "spec.import",
    "spec.lock",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.revoke",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
    "sync.view_status",
  ],

  MARINE_MGR: [
    "page.office.projects",
    "page.office.project.overview",
    "project.read",
    "spec.read",
    "comparison.view",
  ],

  HSEQ_MGR: [
    "page.office.projects",
    "page.office.project.overview",
    "project.read",
    "audit.read",
  ],

  PUR_MGR: [
    "page.office.projects",
    "page.office.project.yards",
    "page.office.project.comparison",
    "project.read",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "tender.award",
  ],

  ACC_MGR: [
    "page.office.projects",
    "page.office.project.comparison",
    "project.read",
    "quote.read.summary",
    "comparison.view",
    "comparison.export",
  ],

  CREW_MGR: ["page.office.projects", "project.read"],

  TECH_SUPDT: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.office.projects",
    "page.office.projects.new",
    "page.office.project.overview",
    "page.office.project.categories",
    "page.office.project.spec",
    "page.office.project.yards",
    "page.office.project.comparison",
    "page.desktop.jobs",
    "page.desktop.sync",
    "project.create",
    "project.read",
    "spec.read",
    "spec.edit",
    "category.read",
    "category.edit",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
    "tender.shortlist",
    "sync.view_status",
    "device.register",
  ],

  MAR_SUPDT: [
    "page.office.projects",
    "page.office.project.overview",
    "page.desktop.jobs",
    "project.read",
    "spec.read",
    "comparison.view",
    "sync.view_status",
    "device.register",
  ],

  PUR_OFF: [
    "page.office.projects",
    "page.office.project.yards",
    "page.office.project.comparison",
    "project.read",
    "yard.invite",
    "yard.view",
    "quote.read.detail",
    "comparison.view",
    "comparison.export",
  ],

  ACC_OFF: [
    "page.office.projects",
    "page.office.project.comparison",
    "project.read",
    "quote.read.summary",
    "comparison.view",
  ],

  INV_CTRL: ["page.office.projects", "project.read"],
  DOC_CTRL: ["page.office.projects", "project.read", "spec.read"],

  MASTER: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
    "spec.read",
    "comparison.view",
    "sync.view_status",
  ],
  CENG: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
    "spec.read",
    "comparison.view",
    "sync.view_status",
  ],
  COFF: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
    "comparison.view",
  ],
  "2ENG": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
    "comparison.view",
  ],
  ETO: [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "2OFF": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "3OFF": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "3ENG": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],
  "4ENG": [
    "page.shipAccess.dashboard",
    "page.shipAccess.jobs",
    "page.shipAccess.jobs.new",
    "ship.job.create",
    "ship.job.read",
    "page.desktop.jobs",
    "project.read",
  ],

  SHIPYARD: [
    "page.yard.quote",
    "page.shipyard.dashboard",
    "page.shipyard.projects",
    "page.shipyard.workshops",
    "page.shipyard.planning",
    "page.shipyard.execution",
    "page.shipyard.commercial",
    "page.shipyard.tender",
    "quote.submit",
    "spec.read",
    "yard.execution.read",
    "yard.execution.manage",
    "yard.job.update",
    "yard.dependency.manage",
  ],
  YARD_PM: [
    "page.shipyard.dashboard",
    "page.shipyard.projects",
    "page.shipyard.workshops",
    "page.shipyard.planning",
    "page.shipyard.execution",
    "page.shipyard.commercial",
    "page.shipyard.tender",
    "yard.execution.read",
    "yard.execution.manage",
    "yard.job.update",
    "yard.dependency.manage",
    "spec.read",
  ],
  YARD_PLAN: [
    "page.shipyard.dashboard",
    "page.shipyard.projects",
    "page.shipyard.planning",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.dependency.manage",
    "yard.job.update",
    "spec.read",
  ],
  YARD_HULL: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.hull",
    "yard.job.update",
  ],
  YARD_PAINT: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.painting",
    "yard.job.update",
  ],
  YARD_MACH: [
    "page.shipyard.workshops",
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.machinery",
    "yard.job.update",
  ],
  YARD_QA: [
    "page.shipyard.execution",
    "page.shipyard.commercial",
    "yard.execution.read",
    "yard.workshop.safety",
    "yard.job.update",
  ],
  YARD_SAFETY: [
    "page.shipyard.execution",
    "yard.execution.read",
    "yard.workshop.safety",
    "yard.job.update",
  ],
  YARD_COMM: [
    "page.shipyard.commercial",
    "page.shipyard.tender",
    "yard.execution.read",
    "yard.workshop.commercial",
    "spec.read",
  ],
  VENDOR: ["quote.read.summary"],
  MAKER: [],
  CLASS: ["project.read", "spec.read"],
  FLAG: ["project.read", "spec.read"],
  AUDITOR: ["project.read", "audit.read"],
  OWNER: ["page.office.projects", "project.read", "quote.read.summary", "comparison.view"],
};

/** Expand DEV_ADMIN wildcard to all permission keys at seed time. */
export function resolveRolePermissionKeys(
  roleCode: string,
  allPermissionKeys: string[],
): string[] {
  const keys = DEFAULT_ROLE_PERMISSIONS[roleCode];
  if (!keys) return [];
  if (keys.includes("*")) return allPermissionKeys;
  return keys;
}

/** Map Next.js path patterns to page permission keys. */
export const PAGE_ROUTE_PERMISSIONS: { pattern: RegExp; permission: string }[] = [
  { pattern: /^\/projects\/new\/?$/, permission: "page.office.projects.new" },
  { pattern: /^\/projects\/?$/, permission: "page.office.projects" },
  { pattern: /^\/projects\/[^/]+\/?$/, permission: "page.office.project.overview" },
  { pattern: /^\/quote\/[^/]+\/?$/, permission: "page.yard.quote" },
  { pattern: /^\/ship-access\/jobs\/new\/?$/, permission: "page.shipAccess.jobs.new" },
  { pattern: /^\/ship-access\/jobs\/?$/, permission: "page.shipAccess.jobs" },
  { pattern: /^\/ship-access\/?$/, permission: "page.shipAccess.dashboard" },
  { pattern: /^\/shipyard\/?$/, permission: "page.shipyard.dashboard" },
  { pattern: /^\/shipyard\/projects(\/.*)?$/, permission: "page.shipyard.projects" },
  { pattern: /^\/shipyard\/workshops(\/.*)?$/, permission: "page.shipyard.workshops" },
  { pattern: /^\/shipyard\/planning(\/.*)?$/, permission: "page.shipyard.planning" },
  { pattern: /^\/shipyard\/execution(\/.*)?$/, permission: "page.shipyard.execution" },
  { pattern: /^\/shipyard\/(commercial|tender|yards)(\/.*)?$/, permission: "page.shipyard.commercial" },
  { pattern: /^\/admin\/?$/, permission: "page.office.admin" },
  { pattern: /^\/admin\/companies(\/.*)?$/, permission: "page.office.admin.companies" },
  { pattern: /^\/admin\/vessels(\/.*)?$/, permission: "page.office.admin.vessels" },
  { pattern: /^\/admin\/employees(\/.*)?$/, permission: "page.office.admin.employees" },
  { pattern: /^\/admin\/access\/?$/, permission: "page.office.admin.access" },
  { pattern: /^\/admin\/users\/?$/, permission: "page.office.admin.users" },
  { pattern: /^\/admin\/roles\/?$/, permission: "page.office.admin.roles" },
  { pattern: /^\/platform\/?$/, permission: "page.platform.admin" },
];

export function pagePermissionForPath(pathname: string): string | null {
  for (const { pattern, permission } of PAGE_ROUTE_PERMISSIONS) {
    if (pattern.test(pathname)) return permission;
  }
  return null;
}

/** Project dashboard tab → page permission. */
export const PROJECT_TAB_PERMISSIONS: Record<string, string> = {
  overview: "page.office.project.overview",
  categories: "page.office.project.categories",
  spec: "page.office.project.spec",
  yards: "page.office.project.yards",
  comparison: "page.office.project.comparison",
};
